"""
特殊名单 (FLXG3D56)
"""

from typing import Optional
from pydantic import BaseModel, Field

class FLXG3D56Response(BaseModel):
    """
    特殊名单 (FLXG3D56)
    特殊名单数据实体类。
    """
    code: Optional[str] = Field(None, description="返回编码")
    data: Optional["SpecialListData"] = Field(None, description="特殊名单响应数据实体类")
    flag_specialList_c: Optional[str] = Field(None, description="特殊名单风险标识：0-无风险，1-有风险")


class SpecialListData(BaseModel):
    """
    特殊名单 (FLXG3D56)
    特殊名单数据实体类。
    """
    swift_number: Optional[str] = Field(None, description="流水号")
    code: Optional[str] = Field(None, description="状态码，00表示查询成功")
    flag_specialList_c: Optional[str] = Field(None, description="特殊名单风险标识：0-无风险，1-有风险")
    sl_id_court_bad: Optional[str] = Field(None, description="通过 id 查询法院失信人: 0(命中), 空(未命中)")
    sl_id_court_executed: Optional[str] = Field(None, description="通过 id 查询法院被执行人: 0(命中), 空(未命中)")
    sl_id_bank_bad: Optional[str] = Field(None, description="通过 id 查询银行(含信用卡)中风险: 0(命中), 空(未命中)")
    sl_id_bank_overdue: Optional[str] = Field(None, description="通过 id 查询银行(含信用卡)一般风险: 0(命中), 空(未命中)")
    sl_id_bank_lost: Optional[str] = Field(None, description="通过 id 查询银行(含信用卡)高风险: 0(命中), 空(未命中)")
    sl_id_nbank_bad: Optional[str] = Field(None, description="通过 id 查询非银(含全部非银类型)中风险: 0(命中), 空(未命中)")
    sl_id_nbank_overdue: Optional[str] = Field(None, description="通过 id 查询非银(含全部非银类型)一般风险: 0(命中), 空(未命中)")
    sl_id_nbank_lost: Optional[str] = Field(None, description="通过 id 查询非银(含全部非银类型)高风险: 0(命中), 空(未命中)")
    sl_id_nbank_nsloan_bad: Optional[str] = Field(None, description="通过 id 查询非银-持牌网络小贷中风险: 0(命中), 空(未命中)")
    sl_id_nbank_nsloan_overdue: Optional[str] = Field(None, description="通过 id 查询非银-持牌网络小贷一般风险: 0(命中), 空(未命中)")
    sl_id_nbank_nsloan_lost: Optional[str] = Field(None, description="通过 id 查询非银-持牌网络小贷高风险: 0(命中), 空(未命中)")
    sl_id_nbank_sloan_bad: Optional[str] = Field(None, description="通过 id 查询非银-持牌小贷中风险: 0(命中), 空(未命中)")
    sl_id_nbank_sloan_overdue: Optional[str] = Field(None, description="通过 id 查询非银-持牌小贷一般风险: 0(命中), 空(未命中)")
    sl_id_nbank_sloan_lost: Optional[str] = Field(None, description="通过 id 查询非银-持牌小贷高风险: 0(命中), 空(未命中)")
    sl_id_nbank_cons_bad: Optional[str] = Field(None, description="通过 id 查询非银-持牌消费金融中风险: 0(命中), 空(未命中)")
    sl_id_nbank_cons_overdue: Optional[str] = Field(None, description="通过 id 查询非银-持牌消费金融一般风险: 0(命中), 空(未命中)")
    sl_id_nbank_cons_lost: Optional[str] = Field(None, description="通过 id 查询非银-持牌消费金融高风险: 0(命中), 空(未命中)")
    sl_id_nbank_finlea_bad: Optional[str] = Field(None, description="通过 id 查询非银-持牌融资租赁中风险: 0(命中), 空(未命中)")
    sl_id_nbank_finlea_overdue: Optional[str] = Field(None, description="通过 id 查询非银-持牌融资租赁一般风险: 0(命中), 空(未命中)")
    sl_id_nbank_finlea_lost: Optional[str] = Field(None, description="通过 id 查询非银-持牌融资租赁高风险: 0(命中), 空(未命中)")
    sl_id_nbank_autofin_bad: Optional[str] = Field(None, description="通过 id 查询非银-持牌汽车金融中风险: 0(命中), 空(未命中)")
    sl_id_nbank_autofin_overdue: Optional[str] = Field(None, description="通过 id 查询非银-持牌汽车金融一般风险: 0(命中), 空(未命中)")
    sl_id_nbank_autofin_lost: Optional[str] = Field(None, description="通过 id 查询非银-持牌汽车金融高风险: 0(命中), 空(未命中)")
    sl_id_nbank_other_bad: Optional[str] = Field(None, description="通过 id 查询非银-其他中风险: 0(命中), 空(未命中)")
    sl_id_nbank_other_overdue: Optional[str] = Field(None, description="通过 id 查询非银-其他一般风险: 0(命中), 空(未命中)")
    sl_id_nbank_other_lost: Optional[str] = Field(None, description="通过 id 查询非银-其他高风险: 0(命中), 空(未命中)")
    sl_cell_bank_bad: Optional[str] = Field(None, description="通过 cell查询银行(含信用卡)中风险: 0(命中), 空(未命中)")
    sl_cell_bank_overdue: Optional[str] = Field(None, description="通过 cell查询银行(含信用卡)一般风险: 0(命中), 空(未命中)")
    sl_cell_bank_lost: Optional[str] = Field(None, description="通过 cell查询银行(含信用卡)高风险: 0(命中), 空(未命中)")
    sl_cell_nbank_bad: Optional[str] = Field(None, description="通过 cell查询非银(含全部非银类型)中风险: 0(命中), 空(未命中)")
    sl_cell_nbank_overdue: Optional[str] = Field(None, description="通过 cell查询非银(含全部非银类型)一般风险: 0(命中), 空(未命中)")
    sl_cell_nbank_lost: Optional[str] = Field(None, description="通过 cell查询非银(含全部非银类型)高风险: 0(命中), 空(未命中)")
    sl_cell_nbank_nsloan_bad: Optional[str] = Field(None, description="通过 cell查询非银-持牌网络小贷中风险: 0(命中), 空(未命中)")
    sl_cell_nbank_nsloan_overdue: Optional[str] = Field(None, description="通过 cell查询非银-持牌网络小贷一般风险: 0(命中), 空(未命中)")
    sl_cell_nbank_nsloan_lost: Optional[str] = Field(None, description="通过 cell查询非银-持牌网络小贷高风险: 0(命中), 空(未命中)")
    sl_cell_nbank_sloan_bad: Optional[str] = Field(None, description="通过 cell查询非银-持牌小贷中风险: 0(命中), 空(未命中)")
    sl_cell_nbank_sloan_overdue: Optional[str] = Field(None, description="通过 cell查询非银-持牌小贷一般风险: 0(命中), 空(未命中)")
    sl_cell_nbank_sloan_lost: Optional[str] = Field(None, description="通过 cell查询非银-持牌小贷高风险: 0(命中), 空(未命中)")
    sl_cell_nbank_cons_bad: Optional[str] = Field(None, description="通过 cell查询非银-持牌消费金融中风险: 0(命中), 空(未命中)")
    sl_cell_nbank_cons_overdue: Optional[str] = Field(None, description="通过 cell查询非银-持牌消费金融一般风险: 0(命中), 空(未命中)")
    sl_cell_nbank_cons_lost: Optional[str] = Field(None, description="通过 cell查询非银-持牌消费金融高风险: 0(命中), 空(未命中)")
    sl_cell_nbank_finlea_bad: Optional[str] = Field(None, description="通过 cell查询非银-持牌融资租赁中风险: 0(命中), 空(未命中)")
    sl_cell_nbank_finlea_overdue: Optional[str] = Field(None, description="通过 cell查询非银-持牌融资租赁一般风险: 0(命中), 空(未命中)")
    sl_cell_nbank_finlea_lost: Optional[str] = Field(None, description="通过 cell查询非银-持牌融资租赁高风险: 0(命中), 空(未命中)")
    sl_cell_nbank_autofin_bad: Optional[str] = Field(None, description="通过 cell查询非银-持牌汽车金融中风险: 0(命中), 空(未命中)")
    sl_cell_nbank_autofin_overdue: Optional[str] = Field(None, description="通过 cell查询非银-持牌汽车金融一般风险: 0(命中), 空(未命中)")
    sl_cell_nbank_autofin_lost: Optional[str] = Field(None, description="通过 cell查询非银-持牌汽车金融高风险: 0(命中), 空(未命中)")
    sl_cell_nbank_other_bad: Optional[str] = Field(None, description="通过 cell查询非银-其他中风险: 0(命中), 空(未命中)")
    sl_cell_nbank_other_overdue: Optional[str] = Field(None, description="通过 cell查询非银-其他一般风险: 0(命中), 空(未命中)")
    sl_cell_nbank_other_lost: Optional[str] = Field(None, description="通过 cell查询非银-其他高风险: 0(命中), 空(未命中)")
    sl_id_court_bad_allnum: Optional[str] = Field(None, description="通过 id 查询法院失信人命中次数: 1-N (返回命中次数)")
    sl_id_court_executed_allnum: Optional[str] = Field(None, description="通过 id 查询法院被执行人命中次数: 1-N (返回命中次数)")
    sl_id_bank_bad_allnum: Optional[str] = Field(None, description="通过 id 查询银行(含信用卡)中风险命中次数: 1-N (返回命中次数)")
    sl_id_bank_overdue_allnum: Optional[str] = Field(None, description="通过 id 查询银行(含信用卡)一般风险命中次数: 1-N (返回命中次数)")
    sl_id_bank_lost_allnum: Optional[str] = Field(None, description="通过 id 查询银行(含信用卡)高风险命中次数: 1-N (返回命中次数)")
    sl_id_nbank_bad_allnum: Optional[str] = Field(None, description="通过 id 查询非银(含全部非银类型)中风险命中次数: 1-N (返回命中次数)")
    sl_id_nbank_overdue_allnum: Optional[str] = Field(None, description="通过 id 查询非银(含全部非银类型)一般风险命中次数: 1-N (返回命中次数)")
    sl_id_nbank_lost_allnum: Optional[str] = Field(None, description="通过 id 查询非银(含全部非银类型)高风险命中次数: 1-N (返回命中次数)")
    sl_id_nbank_nsloan_bad_allnum: Optional[str] = Field(None, description="通过 id 查询非银-持牌网络小贷中风险命中次数: 1-N (返回命中次数)")
    sl_id_nbank_nsloan_overdue_allnum: Optional[str] = Field(None, description="通过 id 查询非银-持牌网络小贷一般风险命中次数: 1-N (返回命中次数)")
    sl_id_nbank_nsloan_lost_allnum: Optional[str] = Field(None, description="通过 id 查询非银-持牌网络小贷高风险命中次数: 1-N (返回命中次数)")
    sl_id_nbank_sloan_bad_allnum: Optional[str] = Field(None, description="通过 id 查询非银-持牌小贷中风险命中次数: 1-N (返回命中次数)")
    sl_id_nbank_sloan_overdue_allnum: Optional[str] = Field(None, description="通过 id 查询非银-持牌小贷一般风险命中次数: 1-N (返回命中次数)")
    sl_id_nbank_sloan_lost_allnum: Optional[str] = Field(None, description="通过 id 查询非银-持牌小贷高风险命中次数: 1-N (返回命中次数)")
    sl_id_nbank_cons_bad_allnum: Optional[str] = Field(None, description="通过 id 查询非银-持牌消费金融中风险命中次数: 1-N (返回命中次数)")
    sl_id_nbank_cons_overdue_allnum: Optional[str] = Field(None, description="通过 id 查询非银-持牌消费金融一般风险命中次数: 1-N (返回命中次数)")
    sl_id_nbank_cons_lost_allnum: Optional[str] = Field(None, description="通过 id 查询非银-持牌消费金融高风险命中次数: 1-N (返回命中次数)")
    sl_id_nbank_finlea_bad_allnum: Optional[str] = Field(None, description="通过 id 查询非银-持牌融资租赁中风险命中次数: 1-N (返回命中次数)")
    sl_id_nbank_finlea_overdue_allnum: Optional[str] = Field(None, description="通过 id 查询非银-持牌融资租赁一般风险命中次数: 1-N (返回命中次数)")
    sl_id_nbank_finlea_lost_allnum: Optional[str] = Field(None, description="通过 id 查询非银-持牌融资租赁高风险命中次数: 1-N (返回命中次数)")
    sl_id_nbank_autofin_bad_allnum: Optional[str] = Field(None, description="通过 id 查询非银-持牌汽车金融中风险命中次数: 1-N (返回命中次数)")
    sl_id_nbank_autofin_overdue_allnum: Optional[str] = Field(None, description="通过 id 查询非银-持牌汽车金融一般风险命中次数: 1-N (返回命中次数)")
    sl_id_nbank_autofin_lost_allnum: Optional[str] = Field(None, description="通过 id 查询非银-持牌汽车金融高风险命中次数: 1-N (返回命中次数)")
    sl_id_nbank_other_bad_allnum: Optional[str] = Field(None, description="通过 id 查询非银-其他中风险命中次数: 1-N (返回命中次数)")
    sl_id_nbank_other_overdue_allnum: Optional[str] = Field(None, description="通过 id 查询非银-其他一般风险命中次数: 1-N (返回命中次数)")
    sl_id_nbank_other_lost_allnum: Optional[str] = Field(None, description="通过 id 查询非银-其他高风险命中次数: 1-N (返回命中次数)")
    sl_cell_bank_bad_allnum: Optional[str] = Field(None, description="通过 cell查询银行(含信用卡)中风险命中次数: 1-N (返回命中次数)")
    sl_cell_bank_overdue_allnum: Optional[str] = Field(None, description="通过 cell查询银行(含信用卡)一般风险命中次数: 1-N (返回命中次数)")
    sl_cell_bank_lost_allnum: Optional[str] = Field(None, description="通过 cell查询银行(含信用卡)高风险命中次数: 1-N (返回命中次数)")
    sl_cell_nbank_bad_allnum: Optional[str] = Field(None, description="通过 cell查询非银(含全部非银类型)中风险命中次数: 1-N (返回命中次数)")
    sl_cell_nbank_overdue_allnum: Optional[str] = Field(None, description="通过 cell 查询非银(含全部非银类型)一般风险命中次数: 1-N (返回命中次数)")
    sl_cell_nbank_lost_allnum: Optional[str] = Field(None, description="通过 cell查询非银(含全部非银类型)高风险命中次数: 1-N (返回命中次数)")
    sl_cell_nbank_nsloan_bad_allnum: Optional[str] = Field(None, description="通过 cell查询非银-持牌网络小贷中风险命中次数: 1-N (返回命中次数)")
    sl_cell_nbank_nsloan_overdue_allnum: Optional[str] = Field(None, description="通过 cell查询非银-持牌网络小贷一般风险命中次数: 1-N (返回命中次数)")
    sl_cell_nbank_nsloan_lost_allnum: Optional[str] = Field(None, description="通过 cell查询非银-持牌网络小贷高风险命中次数: 1-N (返回命中次数)")
    sl_cell_nbank_sloan_bad_allnum: Optional[str] = Field(None, description="通过 cell查询非银-持牌小贷中风险命中次数: 1-N (返回命中次数)")
    sl_cell_nbank_sloan_overdue_allnum: Optional[str] = Field(None, description="通过 cell查询非银-持牌小贷一般风险命中次数: 1-N (返回命中次数)")
    sl_cell_nbank_sloan_lost_allnum: Optional[str] = Field(None, description="通过 cell查询非银-持牌小贷高风险命中次数: 1-N (返回命中次数)")
    sl_cell_nbank_cons_bad_allnum: Optional[str] = Field(None, description="通过 cell查询非银-持牌消费金融中风险命中次数: 1-N (返回命中次数)")
    sl_cell_nbank_cons_overdue_allnum: Optional[str] = Field(None, description="通过 cell查询非银-持牌消费金融一般风险命中次数: 1-N (返回命中次数)")
    sl_cell_nbank_cons_lost_allnum: Optional[str] = Field(None, description="通过 cell查询非银-持牌消费金融高风险命中次数: 1-N (返回命中次数)")
    sl_cell_nbank_finlea_bad_allnum: Optional[str] = Field(None, description="通过 cell查询非银-持牌融资租赁中风险命中次数: 1-N (返回命中次数)")
    sl_cell_nbank_finlea_overdue_allnum: Optional[str] = Field(None, description="通过 cell查询非银-持牌融资租赁一般风险命中次数: 1-N (返回命中次数)")
    sl_cell_nbank_finlea_lost_allnum: Optional[str] = Field(None, description="通过 cell查询非银-持牌融资租赁高风险命中次数: 1-N (返回命中次数)")
    sl_cell_nbank_autofin_bad_allnum: Optional[str] = Field(None, description="通过 cell查询非银-持牌汽车金融中风险命中次数: 1-N (返回命中次数)")
    sl_cell_nbank_autofin_overdue_allnum: Optional[str] = Field(None, description="通过 cell查询非银-持牌汽车金融一般风险命中次数: 1-N (返回命中次数)")
    sl_cell_nbank_autofin_lost_allnum: Optional[str] = Field(None, description="通过 cell查询非银-持牌汽车金融高风险命中次数: 1-N (返回命中次数)")
    sl_cell_nbank_other_bad_allnum: Optional[str] = Field(None, description="通过 cell查询非银-其他中风险命中次数: 1-N (返回命中次数)")
    sl_cell_nbank_other_overdue_allnum: Optional[str] = Field(None, description="通过 cell查询非银-其他一般风险命中次数: 1-N (返回命中次数)")
    sl_cell_nbank_other_lost_allnum: Optional[str] = Field(None, description="通过 cell查询非银-其他高风险命中次数: 1-N (返回命中次数)")
    sl_id_court_bad_time: Optional[str] = Field(None, description="通过 id 查询法院失信人距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_id_court_executed_time: Optional[str] = Field(None, description="通过 id 查询法院被执行人距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_id_bank_bad_time: Optional[str] = Field(None, description="通过 id 查询银行(含信用卡)中风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_id_bank_overdue_time: Optional[str] = Field(None, description="通过 id 查询银行(含信用卡)一般风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_id_bank_lost_time: Optional[str] = Field(None, description="通过 id 查询银行(含信用卡)高风险距今时间: 0-N(单位:年), 返回最近一次命中")
    sl_id_nbank_bad_time: Optional[str] = Field(None, description="通过 id 查询非银(含全部非银类型)中风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_id_nbank_overdue_time: Optional[str] = Field(None, description="通过 id 查询非银(含全部非银类型)一般风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_id_nbank_lost_time: Optional[str] = Field(None, description="通过 id 查询非银(含全部非银类型)高风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_id_nbank_nsloan_bad_time: Optional[str] = Field(None, description="通过 id 查询非银-持牌网络小贷中风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_id_nbank_nsloan_overdue_time: Optional[str] = Field(None, description="通过 id 查询非银-持牌网络小贷一般风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_id_nbank_nsloan_lost_time: Optional[str] = Field(None, description="通过 id 查询非银-持牌网络小贷高风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_id_nbank_sloan_bad_time: Optional[str] = Field(None, description="通过 id 查询非银-持牌小贷中风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_id_nbank_sloan_overdue_time: Optional[str] = Field(None, description="通过 id 查询非银-持牌小贷一般风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_id_nbank_sloan_lost_time: Optional[str] = Field(None, description="通过 id 查询非银-持牌小贷高风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_id_nbank_cons_bad_time: Optional[str] = Field(None, description="通过 id 查询非银-持牌消费金融中风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_id_nbank_cons_overdue_time: Optional[str] = Field(None, description="通过 id 查询非银-持牌消费金融一般风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_id_nbank_cons_lost_time: Optional[str] = Field(None, description="通过 id 查询非银-持牌消费金融高风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_id_nbank_finlea_bad_time: Optional[str] = Field(None, description="通过 id 查询非银-持牌融资租赁中风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_id_nbank_finlea_overdue_time: Optional[str] = Field(None, description="通过 id 查询非银-持牌融资租赁一般风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_id_nbank_finlea_lost_time: Optional[str] = Field(None, description="通过 id 查询非银-持牌融资租赁高风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_id_nbank_autofin_bad_time: Optional[str] = Field(None, description="通过 id 查询非银-持牌汽车金融中风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_id_nbank_autofin_overdue_time: Optional[str] = Field(None, description="通过 id 查询非银-持牌汽车金融一般风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_id_nbank_autofin_lost_time: Optional[str] = Field(None, description="通过 id 查询非银-持牌汽车金融高风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_id_nbank_other_bad_time: Optional[str] = Field(None, description="通过 id 查询非银-其他中风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_id_nbank_other_overdue_time: Optional[str] = Field(None, description="通过 id 查询非银-其他一般风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_id_nbank_other_lost_time: Optional[str] = Field(None, description="通过 id 查询非银-其他高风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_cell_bank_bad_time: Optional[str] = Field(None, description="通过 cell查询银行(含信用卡)中风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_cell_bank_overdue_time: Optional[str] = Field(None, description="通过 cell查询银行(含信用卡)一般风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_cell_bank_lost_time: Optional[str] = Field(None, description="通过 cell查询银行(含信用卡)高风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_cell_nbank_bad_time: Optional[str] = Field(None, description="通过 cell查询非银(含全部非银类型)中风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_cell_nbank_overdue_time: Optional[str] = Field(None, description="通过 cell 查询非银(含全部非银类型)一般风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_cell_nbank_lost_time: Optional[str] = Field(None, description="通过 cell查询非银(含全部非银类型)高风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_cell_nbank_nsloan_bad_time: Optional[str] = Field(None, description="通过 cell查询非银-持牌网络小贷中风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_cell_nbank_nsloan_overdue_time: Optional[str] = Field(None, description="通过 cell查询非银-持牌网络小贷一般风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_cell_nbank_nsloan_lost_time: Optional[str] = Field(None, description="通过 cell查询非银-持牌网络小贷高风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_cell_nbank_sloan_bad_time: Optional[str] = Field(None, description="通过 cell查询非银-持牌小贷中风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_cell_nbank_sloan_overdue_time: Optional[str] = Field(None, description="通过 cell查询非银-持牌小贷一般风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_cell_nbank_sloan_lost_time: Optional[str] = Field(None, description="通过 cell查询非银-持牌小贷高风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_cell_nbank_cons_bad_time: Optional[str] = Field(None, description="通过 cell查询非银-持牌消费金融中风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_cell_nbank_cons_overdue_time: Optional[str] = Field(None, description="通过 cell查询非银-持牌消费金融一般风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_cell_nbank_cons_lost_time: Optional[str] = Field(None, description="通过 cell查询非银-持牌消费金融高风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_cell_nbank_finlea_bad_time: Optional[str] = Field(None, description="通过 cell查询非银-持牌融资租赁中风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_cell_nbank_finlea_overdue_time: Optional[str] = Field(None, description="通过 cell查询非银-持牌融资租赁一般风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_cell_nbank_finlea_lost_time: Optional[str] = Field(None, description="通过 cell查询非银-持牌融资租赁高风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_cell_nbank_autofin_bad_time: Optional[str] = Field(None, description="通过 cell查询非银-持牌汽车金融中风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_cell_nbank_autofin_overdue_time: Optional[str] = Field(None, description="通过 cell查询非银-持牌汽车金融一般风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_cell_nbank_autofin_lost_time: Optional[str] = Field(None, description="通过 cell查询非银-持牌汽车金融高风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_cell_nbank_other_bad_time: Optional[str] = Field(None, description="通过 cell查询非银-其他中风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_cell_nbank_other_overdue_time: Optional[str] = Field(None, description="通过 cell查询非银-其他一般风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")
    sl_cell_nbank_other_lost_time: Optional[str] = Field(None, description="通过 cell查询非银-其他高风险距今时间: 0-N(单位:年), 返回最近一次命中距查询时间")