"""
借贷行为验证 (JRZQ8203)
"""

from typing import Optional
from pydantic import BaseModel, Field

class JRZQ8203Response(BaseModel):
    """
    借贷行为验证响应数据实体类
    包含按 身份证号 和按 手机号 查询的各类借贷行为统计数据。
    """
    code: Optional[str] = Field(None, description="返回编码")
    data: Optional["LoanBehaviorVerificationData"] = Field(None, description="借贷行为验证响应数据实体类")
    flag_totalloan: Optional[str] = Field(None, description="借贷行为验证产品输出标识：1(输出成功)，0(未匹配上无输出)，98(用户输入信息不足)，99(系统异常)")



class LoanBehaviorVerificationData(BaseModel):
    """
    借贷行为验证响应数据实体类
    包含按 身份证号 和按 手机号 查询的各类借贷行为统计数据。
    """
    swift_number: Optional[str] = Field(None, description="流水号")
    code: Optional[str] = Field(None, description="状态码")
    flag_totalloan: Optional[str] = Field(None, description="借贷行为验证产品输出标识")

    # 按身份证号查询
    tl_id_eletail_lasttime: Optional[str] = Field(None, description="按身份证号查询，最近一次线上小额现金贷借贷时间")
    tl_id_eletail_lasttype: Optional[str] = Field(None, description="按身份证号查询，最近一次线上小额现金贷的机构类型")
    tl_id_eletail_num: Optional[str] = Field(None, description="按身份证号查询，预测近1年，在线上小额现金贷的新增核准借贷次数")
    tl_id_eletail_org: Optional[str] = Field(None, description="按身份证号查询，预测近1年，在线上小额现金贷的新增核准借贷机构数")
    tl_id_m1_nbank_passnum: Optional[str] = Field(None, description="按身份证号查询，预测近1个月，在非银机构新增核准借贷次数")
    tl_id_m1_nbank_passorg: Optional[str] = Field(None, description="按身份证号查询，预测近1个月，在非银机构新增核准借贷机构数")
    tl_id_m1_nbank_passlendamt: Optional[str] = Field(None, description="按身份证号查询，预测近1个月，在非银机构新增核准借贷等级")
    tl_id_m3_nbank_passnum: Optional[str] = Field(None, description="按身份证号查询，预测近3个月，在非银机构新增核准借贷次数")
    tl_id_m3_nbank_passorg: Optional[str] = Field(None, description="按身份证号查询，预测近3个月，在非银机构新增核准借贷机构数")
    tl_id_m3_nbank_passlendamt: Optional[str] = Field(None, description="按身份证号查询，预测近3个月，在非银机构新增核准借贷等级")
    tl_id_m6_nbank_passnum: Optional[str] = Field(None, description="按身份证号查询，预测近6个月，在非银机构新增核准借贷次数")
    tl_id_m6_nbank_passorg: Optional[str] = Field(None, description="按身份证号查询，预测近6个月，在非银机构新增核准借贷机构数")
    tl_id_m6_nbank_passlendamt: Optional[str] = Field(None, description="按身份证号查询，预测近6个月，在非银机构新增核准借贷等级")
    tl_id_m9_nbank_passnum: Optional[str] = Field(None, description="按身份证号查询，预测近9个月，在非银机构新增核准借贷次数")
    tl_id_m9_nbank_passorg: Optional[str] = Field(None, description="按身份证号查询，预测近9个月，在非银机构新增核准借贷机构数")
    tl_id_m9_nbank_passlendamt: Optional[str] = Field(None, description="按身份证号查询，预测近9个月，在非银机构新增核准借贷等级")
    tl_id_m12_nbank_passnum: Optional[str] = Field(None, description="按身份证号查询，预测近12个月，在非银机构新增核准借贷次数")
    tl_id_m12_nbank_passorg: Optional[str] = Field(None, description="按身份证号查询，预测近12个月，在非银机构新增核准借贷机构数")
    tl_id_m12_nbank_passlendamt: Optional[str] = Field(None, description="按身份证号查询，预测近12个月，在非银机构新增核准借贷等级")
    tl_id_t0_nbank_num: Optional[str] = Field(None, description="按身份证号查询，预测在当前时间，近一年在非银机构的新增核准借贷次数")
    tl_id_t0_nbank_org: Optional[str] = Field(None, description="按身份证号查询，预测在当前时间，近一年在非银机构的新增核准借贷机构数")
    tl_id_t0_nbank_lendamt: Optional[str] = Field(None, description="按身份证号查询，预测在当前时间，近一年在非银机构的新增核准借贷等级")
    tl_id_t0_nbank_reamt: Optional[str] = Field(None, description="按身份证号查询，预测在当前时间，近一年在非银机构的应还款等级")
    tl_id_t1_nbank_num: Optional[str] = Field(None, description="按身份证号查询，预测1个月前，近一年在非银机构的新增核准借贷次数")
    tl_id_t1_nbank_org: Optional[str] = Field(None, description="按身份证号查询，预测1个月前，近一年在非银机构的新增核准借贷机构数")
    tl_id_t1_nbank_lendamt: Optional[str] = Field(None, description="按身份证号查询，预测1个月前，近一年在非银机构的新增核准借贷等级")
    tl_id_t1_nbank_reamt: Optional[str] = Field(None, description="按身份证号查询，预测1个月前，近一年在非银机构的应还款等级")
    tl_id_t2_nbank_num: Optional[str] = Field(None, description="按身份证号查询，预测2个月前，近一年在非银机构的新增核准借贷次数")
    tl_id_t2_nbank_org: Optional[str] = Field(None, description="按身份证号查询，预测2个月前，近一年在非银机构的新增核准借贷机构数")
    tl_id_t2_nbank_lendamt: Optional[str] = Field(None, description="按身份证号查询，预测2个月前，近一年在非银机构的新增核准借贷等级")
    tl_id_t2_nbank_reamt: Optional[str] = Field(None, description="按身份证号查询，预测2个月前，近一年在非银机构的应还款等级")
    tl_id_t3_nbank_num: Optional[str] = Field(None, description="按身份证号查询，预测3个月前，近一年在非银机构的新增核准借贷次数")
    tl_id_t3_nbank_org: Optional[str] = Field(None, description="按身份证号查询，预测3个月前，近一年在非银机构的新增核准借贷机构数")
    tl_id_t3_nbank_lendamt: Optional[str] = Field(None, description="按身份证号查询，预测3个月前，近一年在非银机构的新增核准借贷等级")
    tl_id_t3_nbank_reamt: Optional[str] = Field(None, description="按身份证号查询，预测3个月前，近一年在非银机构的应还款等级")
    tl_id_t4_nbank_num: Optional[str] = Field(None, description="按身份证号查询，预测4个月前，近一年在非银机构的新增核准借贷次数")
    tl_id_t4_nbank_org: Optional[str] = Field(None, description="按身份证号查询，预测4个月前，近一年在非银机构的新增核准借贷机构数")
    tl_id_t4_nbank_lendamt: Optional[str] = Field(None, description="按身份证号查询，预测4个月前，近一年在非银机构的新增核准借贷等级")
    tl_id_t4_nbank_reamt: Optional[str] = Field(None, description="按身份证号查询，预测4个月前，近一年在非银机构的应还款等级")
    tl_id_t5_nbank_num: Optional[str] = Field(None, description="按身份证号查询，预测5个月前，近一年在非银机构的新增核准借贷次数")
    tl_id_t5_nbank_org: Optional[str] = Field(None, description="按身份证号查询，预测5个月前，近一年在非银机构的新增核准借贷机构数")
    tl_id_t5_nbank_lendamt: Optional[str] = Field(None, description="按身份证号查询，预测5个月前，近一年在非银机构的新增核准借贷等级")
    tl_id_t5_nbank_reamt: Optional[str] = Field(None, description="按身份证号查询，预测5个月前，近一年在非银机构的应还款等级")
    tl_id_t6_nbank_num: Optional[str] = Field(None, description="按身份证号查询，预测6个月前，近一年在非银机构的新增核准借贷次数")
    tl_id_t6_nbank_org: Optional[str] = Field(None, description="按身份证号查询，预测6个月前，近一年在非银机构的新增核准借贷机构数")
    tl_id_t6_nbank_lendamt: Optional[str] = Field(None, description="按身份证号查询，预测6个月前，近一年在非银机构的新增核准借贷等级")
    tl_id_t6_nbank_reamt: Optional[str] = Field(None, description="按身份证号查询，预测6个月前，近一年在非银机构的应还款等级")
    tl_id_t7_nbank_num: Optional[str] = Field(None, description="按身份证号查询，预测7个月前，近一年在非银机构的新增核准借贷次数")
    tl_id_t7_nbank_org: Optional[str] = Field(None, description="按身份证号查询，预测7个月前，近一年在非银机构的新增核准借贷机构数")
    tl_id_t7_nbank_lendamt: Optional[str] = Field(None, description="按身份证号查询，预测7个月前，近一年在非银机构的新增核准借贷等级")
    tl_id_t7_nbank_reamt: Optional[str] = Field(None, description="按身份证号查询，预测7个月前，近一年在非银机构的应还款等级")
    tl_id_t8_nbank_num: Optional[str] = Field(None, description="按身份证号查询，预测8个月前，近一年在非银机构的新增核准借贷次数")
    tl_id_t8_nbank_org: Optional[str] = Field(None, description="按身份证号查询，预测8个月前，近一年在非银机构的新增核准借贷机构数")
    tl_id_t8_nbank_lendamt: Optional[str] = Field(None, description="按身份证号查询，预测8个月前，近一年在非银机构的新增核准借贷等级")
    tl_id_t8_nbank_reamt: Optional[str] = Field(None, description="按身份证号查询，预测8个月前，近一年在非银机构的应还款等级")
    tl_id_t9_nbank_num: Optional[str] = Field(None, description="按身份证号查询，预测9个月前，近一年在非银机构的新增核准借贷次数")
    tl_id_t9_nbank_org: Optional[str] = Field(None, description="按身份证号查询，预测9个月前，近一年在非银机构的新增核准借贷机构数")
    tl_id_t9_nbank_lendamt: Optional[str] = Field(None, description="按身份证号查询，预测9个月前，近一年在非银机构的新增核准借贷等级")
    tl_id_t9_nbank_reamt: Optional[str] = Field(None, description="按身份证号查询，预测9个月前，近一年在非银机构的应还款等级")
    tl_id_t10_nbank_num: Optional[str] = Field(None, description="按身份证号查询，预测10个月前，近一年在非银机构的新增核准借贷次数")
    tl_id_t10_nbank_org: Optional[str] = Field(None, description="按身份证号查询，预测10个月前，近一年在非银机构的新增核准借贷机构数")
    tl_id_t10_nbank_lendamt: Optional[str] = Field(None, description="按身份证号查询，预测10个月前，近一年在非银机构的新增核准借贷等级")
    tl_id_t10_nbank_reamt: Optional[str] = Field(None, description="按身份证号查询，预测10个月前，近一年在非银机构的应还款等级")
    tl_id_t11_nbank_num: Optional[str] = Field(None, description="按身份证号查询，预测11个月前，近一年在非银机构的新增核准借贷次数")
    tl_id_t11_nbank_org: Optional[str] = Field(None, description="按身份证号查询，预测11个月前，近一年在非银机构的新增核准借贷机构数")
    tl_id_t11_nbank_lendamt: Optional[str] = Field(None, description="按身份证号查询，预测11个月前，近一年在非银机构的新增核准借贷等级")
    tl_id_t11_nbank_reamt: Optional[str] = Field(None, description="按身份证号查询，预测11个月前，近一年在非银机构的应还款等级")

    # 按手机号查询
    tl_cell_eletail_lasttime: Optional[str] = Field(None, description="按手机号查询，最近一次线上小额现金贷借贷时间")
    tl_cell_eletail_lasttype: Optional[str] = Field(None, description="按手机号查询，最近一次线上小额现金贷的机构类型")
    tl_cell_eletail_num: Optional[str] = Field(None, description="按手机号查询，预测近1年，在线上小额现金贷的新增核准借贷次数")
    tl_cell_eletail_org: Optional[str] = Field(None, description="按手机号查询，预测近1年，在线上小额现金贷的新增核准借贷机构数")
    tl_cell_m1_nbank_passnum: Optional[str] = Field(None, description="按手机号查询，预测近1个月，在非银机构新增核准借贷次数")
    tl_cell_m1_nbank_passorg: Optional[str] = Field(None, description="按手机号查询，预测近1个月，在非银机构新增核准借贷机构数")
    tl_cell_m1_nbank_passlendamt: Optional[str] = Field(None, description="按手机号查询，预测近1个月，在非银机构新增核准借贷等级")
    tl_cell_m3_nbank_passnum: Optional[str] = Field(None, description="按手机号查询，预测近3个月，在非银机构新增核准借贷次数")
    tl_cell_m3_nbank_passorg: Optional[str] = Field(None, description="按手机号查询，预测近3个月，在非银机构新增核准借贷机构数")
    tl_cell_m3_nbank_passlendamt: Optional[str] = Field(None, description="按手机号查询，预测近3个月，在非银机构新增核准借贷等级")
    tl_cell_m6_nbank_passnum: Optional[str] = Field(None, description="按手机号查询，预测近6个月，在非银机构新增核准借贷次数")
    tl_cell_m6_nbank_passorg: Optional[str] = Field(None, description="按手机号查询，预测近6个月，在非银机构新增核准借贷机构数")
    tl_cell_m6_nbank_passlendamt: Optional[str] = Field(None, description="按手机号查询，预测近6个月，在非银机构新增核准借贷等级")
    tl_cell_m9_nbank_passnum: Optional[str] = Field(None, description="按手机号查询，预测近9个月，在非银机构新增核准借贷次数")
    tl_cell_m9_nbank_passorg: Optional[str] = Field(None, description="按手机号查询，预测近9个月，在非银机构新增核准借贷机构数")
    tl_cell_m9_nbank_passlendamt: Optional[str] = Field(None, description="按手机号查询，预测近9个月，在非银机构新增核准借贷等级")
    tl_cell_m12_nbank_passnum: Optional[str] = Field(None, description="按手机号查询，预测近12个月，在非银机构新增核准借贷次数")
    tl_cell_m12_nbank_passorg: Optional[str] = Field(None, description="按手机号查询，预测近12个月，在非银机构新增核准借贷机构数")
    tl_cell_m12_nbank_passlendamt: Optional[str] = Field(None, description="按手机号查询，预测近12个月，在非银机构新增核准借贷等级")
    tl_cell_t0_nbank_num: Optional[str] = Field(None, description="按手机号查询，预测在当前时间，近一年在非银机构的新增核准借贷次数")
    tl_cell_t0_nbank_org: Optional[str] = Field(None, description="按手机号查询，预测在当前时间，近一年在非银机构的新增核准借贷机构数")
    tl_cell_t0_nbank_lendamt: Optional[str] = Field(None, description="按手机号查询，预测在当前时间，近一年在非银机构的新增核准借贷等级")
    tl_cell_t0_nbank_reamt: Optional[str] = Field(None, description="按手机号查询，预测在当前时间，近一年在非银机构的应还款等级")
    tl_cell_t1_nbank_num: Optional[str] = Field(None, description="按手机号查询，预测1个月前，近一年在非银机构的新增核准借贷次数")
    tl_cell_t1_nbank_org: Optional[str] = Field(None, description="按手机号查询，预测1个月前，近一年在非银机构的新增核准借贷机构数")
    tl_cell_t1_nbank_lendamt: Optional[str] = Field(None, description="按手机号查询，预测1个月前，近一年在非银机构的新增核准借贷等级")
    tl_cell_t1_nbank_reamt: Optional[str] = Field(None, description="按手机号查询，预测1个月前，近一年在非银机构的应还款等级")
    tl_cell_t2_nbank_num: Optional[str] = Field(None, description="按手机号查询，预测2个月前，近一年在非银机构的新增核准借贷次数")
    tl_cell_t2_nbank_org: Optional[str] = Field(None, description="按手机号查询，预测2个月前，近一年在非银机构的新增核准借贷机构数")
    tl_cell_t2_nbank_lendamt: Optional[str] = Field(None, description="按手机号查询，预测2个月前，近一年在非银机构的新增核准借贷等级")
    tl_cell_t2_nbank_reamt: Optional[str] = Field(None, description="按手机号查询，预测2个月前，近一年在非银机构的应还款等级")
    tl_cell_t3_nbank_num: Optional[str] = Field(None, description="按手机号查询，预测3个月前，近一年在非银机构的新增核准借贷次数")
    tl_cell_t3_nbank_org: Optional[str] = Field(None, description="按手机号查询，预测3个月前，近一年在非银机构的新增核准借贷机构数")
    tl_cell_t3_nbank_lendamt: Optional[str] = Field(None, description="按手机号查询，预测3个月前，近一年在非银机构的新增核准借贷等级")
    tl_cell_t3_nbank_reamt: Optional[str] = Field(None, description="按手机号查询，预测3个月前，近一年在非银机构的应还款等级")
    tl_cell_t4_nbank_num: Optional[str] = Field(None, description="按手机号查询，预测4个月前，近一年在非银机构的新增核准借贷次数")
    tl_cell_t4_nbank_org: Optional[str] = Field(None, description="按手机号查询，预测4个月前，近一年在非银机构的新增核准借贷机构数")
    tl_cell_t4_nbank_lendamt: Optional[str] = Field(None, description="按手机号查询，预测4个月前，近一年在非银机构的新增核准借贷等级")
    tl_cell_t4_nbank_reamt: Optional[str] = Field(None, description="按手机号查询，预测4个月前，近一年在非银机构的应还款等级")
    tl_cell_t5_nbank_num: Optional[str] = Field(None, description="按手机号查询，预测5个月前，近一年在非银机构的新增核准借贷次数")
    tl_cell_t5_nbank_org: Optional[str] = Field(None, description="按手机号查询，预测5个月前，近一年在非银机构的新增核准借贷机构数")
    tl_cell_t5_nbank_lendamt: Optional[str] = Field(None, description="按手机号查询，预测5个月前，近一年在非银机构的新增核准借贷等级")
    tl_cell_t5_nbank_reamt: Optional[str] = Field(None, description="按手机号查询，预测5个月前，近一年在非银机构的应还款等级")
    tl_cell_t6_nbank_num: Optional[str] = Field(None, description="按手机号查询，预测6个月前，近一年在非银机构的新增核准借贷次数")
    tl_cell_t6_nbank_org: Optional[str] = Field(None, description="按手机号查询，预测6个月前，近一年在非银机构的新增核准借贷机构数")
    tl_cell_t6_nbank_lendamt: Optional[str] = Field(None, description="按手机号查询，预测6个月前，近一年在非银机构的新增核准借贷等级")
    tl_cell_t6_nbank_reamt: Optional[str] = Field(None, description="按手机号查询，预测6个月前，近一年在非银机构的应还款等级")
    tl_cell_t7_nbank_num: Optional[str] = Field(None, description="按手机号查询，预测7个月前，近一年在非银机构的新增核准借贷次数")
    tl_cell_t7_nbank_org: Optional[str] = Field(None, description="按手机号查询，预测7个月前，近一年在非银机构的新增核准借贷机构数")
    tl_cell_t7_nbank_lendamt: Optional[str] = Field(None, description="按手机号查询，预测7个月前，近一年在非银机构的新增核准借贷等级")
    tl_cell_t7_nbank_reamt: Optional[str] = Field(None, description="按手机号查询，预测7个月前，近一年在非银机构的应还款等级")
    tl_cell_t8_nbank_num: Optional[str] = Field(None, description="按手机号查询，预测8个月前，近一年在非银机构的新增核准借贷次数")
    tl_cell_t8_nbank_org: Optional[str] = Field(None, description="按手机号查询，预测8个月前，近一年在非银机构的新增核准借贷机构数")
    tl_cell_t8_nbank_lendamt: Optional[str] = Field(None, description="按手机号查询，预测8个月前，近一年在非银机构的新增核准借贷等级")
    tl_cell_t8_nbank_reamt: Optional[str] = Field(None, description="按手机号查询，预测8个月前，近一年在非银机构的应还款等级")
    tl_cell_t9_nbank_num: Optional[str] = Field(None, description="按手机号查询，预测9个月前，近一年在非银机构的新增核准借贷次数")
    tl_cell_t9_nbank_org: Optional[str] = Field(None, description="按手机号查询，预测9个月前，近一年在非银机构的新增核准借贷机构数")
    tl_cell_t9_nbank_lendamt: Optional[str] = Field(None, description="按手机号查询，预测9个月前，近一年在非银机构的新增核准借贷等级")
    tl_cell_t9_nbank_reamt: Optional[str] = Field(None, description="按手机号查询，预测9个月前，近一年在非银机构的应还款等级")
    tl_cell_t10_nbank_num: Optional[str] = Field(None, description="按手机号查询，预测10个月前，近一年在非银机构的新增核准借贷次数")
    tl_cell_t10_nbank_org: Optional[str] = Field(None, description="按手机号查询，预测10个月前，近一年在非银机构的新增核准借贷机构数")
    tl_cell_t10_nbank_lendamt: Optional[str] = Field(None, description="按手机号查询，预测10个月前，近一年在非银机构的新增核准借贷等级")
    tl_cell_t10_nbank_reamt: Optional[str] = Field(None, description="按手机号查询，预测10个月前，近一年在非银机构的应还款等级")
    tl_cell_t11_nbank_num: Optional[str] = Field(None, description="按手机号查询，预测11个月前，近一年在非银机构的新增核准借贷次数")
    tl_cell_t11_nbank_org: Optional[str] = Field(None, description="按手机号查询，预测11个月前，近一年在非银机构的新增核准借贷机构数")
    tl_cell_t11_nbank_lendamt: Optional[str] = Field(None, description="按手机号查询，预测11个月前，近一年在非银机构的新增核准借贷等级")
    tl_cell_t11_nbank_reamt: Optional[str] = Field(None, description="按手机号查询，预测11个月前，近一年在非银机构的应还款等级")