"""
借贷意向验证 (JRZQ0A03)
"""

from typing import Optional, Any
from pydantic import BaseModel, Field

class JRZQ0A03Response(BaseModel):
    """
    借贷意向验证响应数据实体类。
    包含按身份证号(_id_)和按手机号(_cell_)查询，
    以及按时间维度(d7, d15, m1, m3, m6, m12)和机构类型等细分的全部字段。
    """
    code: Optional[str] = Field(None, description="返回编码")
    data: Optional["LoanIntentionVerificationData"] = Field(None, description="借贷意向验证响应数据实体类")
    flag_applyloanstr: Optional[str] = Field(None, description="产品输出标识: 1(输出成功),0(未匹配上无输出),98(用户输入信息不足),99(系统异常)")

class LoanIntentionVerificationData(BaseModel):
    """
    借贷意向验证响应数据实体类。
    包含按身份证号(_id_)和按手机号(_cell_)查询，
    以及按时间维度(d7, d15, m1, m3, m6, m12)和机构类型等细分的全部字段。
    """
    swift_number: Optional[str] = Field(None, description="流水号")
    code: Optional[str] = Field(None, description="状态码")
    flag_applyloanstr: Optional[str] = Field(None, description="产品输出标识: 1(输出成功),0(未匹配上无输出),98(用户输入信息不足),99(系统异常)")

    # 近7天数据 (按身份证号查询)
    als_d7_id_pdl_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天申请线上小额现金贷的次数")
    als_d7_id_pdl_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天申请线上小额现金贷的机构数")
    als_d7_id_caon_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天申请线上现金分期的次数")
    als_d7_id_caon_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天申请线上现金分期的机构数")
    als_d7_id_rel_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天申请信用卡（类信用卡）的次数")
    als_d7_id_rel_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天申请信用卡（类信用卡）的机构数")
    als_d7_id_caoff_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天申请线下现金分期的次数")
    als_d7_id_caoff_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天申请线下现金分期的机构数")
    als_d7_id_cooff_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天申请线下消费分期的次数")
    als_d7_id_cooff_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天申请线下消费分期的机构数")
    als_d7_id_af_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天申请汽车金融的次数")
    als_d7_id_af_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天申请汽车金融的机构数")
    als_d7_id_coon_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天申请线上消费分期的次数")
    als_d7_id_coon_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天申请线上消费分期的机构数")
    als_d7_id_oth_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天申请其他的次数")
    als_d7_id_oth_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天申请其他的机构数")
    als_d7_id_bank_selfnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在本机构(本机构为银行)的申请次数")
    als_d7_id_bank_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在银行机构申请次数")
    als_d7_id_bank_tra_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在银行机构-传统银行申请次数")
    als_d7_id_bank_ret_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在银行机构-网络零售银行申请次数")
    als_d7_id_bank_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在银行机构申请机构数")
    als_d7_id_bank_tra_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在银行机构-传统银行申请机构数")
    als_d7_id_bank_ret_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在银行机构-网络零售银行申请机构数")
    als_d7_id_bank_week_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在银行机构周末申请次数")
    als_d7_id_bank_week_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在银行机构周末申请机构数")
    als_d7_id_bank_night_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在银行机构夜间申请次数")
    als_d7_id_bank_night_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在银行机构夜间申请机构数")
    als_d7_id_nbank_selfnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在本机构(本机构为非银)申请次数")
    als_d7_id_nbank_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构申请次数")
    als_d7_id_nbank_p2p_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构-改制机构申请次数")
    als_d7_id_nbank_mc_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构-小贷机构申请次数")
    als_d7_id_nbank_ca_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构-现金类分期机构申请次数")
    als_d7_id_nbank_cf_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构-消费类分期机构申请次数")
    als_d7_id_nbank_com_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构-代偿类分期机构申请次数")
    als_d7_id_nbank_oth_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构-其他申请次数")
    als_d7_id_nbank_nsloan_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构-持牌网络小贷机构申请次数")
    als_d7_id_nbank_autofin_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构-持牌汽车金融机构申请次数")
    als_d7_id_nbank_sloan_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构-持牌小贷机构申请次数")
    als_d7_id_nbank_cons_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构-持牌消费金融机构申请次数")
    als_d7_id_nbank_finlea_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构-持牌融资租赁机构申请次数")
    als_d7_id_nbank_else_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构-其他申请次数")
    als_d7_id_nbank_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构申请机构数")
    als_d7_id_nbank_p2p_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构-改制机构申请机构数")
    als_d7_id_nbank_mc_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构-小贷申请机构数")
    als_d7_id_nbank_ca_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构-现金类分期申请机构数")
    als_d7_id_nbank_cf_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构-消费类分期申请机构数")
    als_d7_id_nbank_com_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构-代偿类分期申请机构数")
    als_d7_id_nbank_oth_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构-其他申请机构数")
    als_d7_id_nbank_nsloan_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构-持牌网络小贷机构申请机构数")
    als_d7_id_nbank_autofin_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构-持牌汽车金融机构申请机构数")
    als_d7_id_nbank_sloan_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构-持牌小贷机构申请机构数")
    als_d7_id_nbank_cons_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构-持牌消费金融机构申请机构数")
    als_d7_id_nbank_finlea_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构-持牌融资租赁机构申请机构数")
    als_d7_id_nbank_else_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构-其他申请机构数")
    als_d7_id_nbank_week_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构周末申请次数")
    als_d7_id_nbank_week_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构周末申请机构数")
    als_d7_id_nbank_night_allnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构夜间申请次数")
    als_d7_id_nbank_night_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 7 天在非银机构夜间申请机构数")

    # 近7天数据 (按手机号查询)
    als_d7_cell_pdl_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天申请线上小额现金贷的次数")
    als_d7_cell_pdl_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天申请线上小额现金贷的机构数")
    als_d7_cell_caon_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天申请线上现金分期的次数")
    als_d7_cell_caon_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天申请线上现金分期的机构数")
    als_d7_cell_rel_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天申请信用卡（类信用卡）的次数")
    als_d7_cell_rel_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天申请信用卡（类信用卡）的机构数")
    als_d7_cell_caoff_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天申请线下现金分期的次数")
    als_d7_cell_caoff_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天申请线下现金分期的机构数")
    als_d7_cell_cooff_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天申请线下消费分期的次数")
    als_d7_cell_cooff_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天申请线下消费分期的机构数")
    als_d7_cell_af_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天申请汽车金融的次数")
    als_d7_cell_af_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天申请汽车金融的机构数")
    als_d7_cell_coon_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天申请线上消费分期的次数")
    als_d7_cell_coon_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天申请线上消费分期的机构数")
    als_d7_cell_oth_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天申请其他的次数")
    als_d7_cell_oth_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天申请其他的机构数")
    als_d7_cell_bank_selfnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在本机构(本机构为银行)的申请次数")
    als_d7_cell_bank_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在银行机构申请次数")
    als_d7_cell_bank_tra_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在银行机构-传统银行申请次数")
    als_d7_cell_bank_ret_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在银行机构-网络零售银行申请次数")
    als_d7_cell_bank_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在银行机构申请机构数")
    als_d7_cell_bank_tra_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在银行机构-传统银行申请机构数")
    als_d7_cell_bank_ret_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在银行机构-网络零售银行申请机构数")
    als_d7_cell_bank_week_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在银行机构周末申请次数")
    als_d7_cell_bank_week_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在银行机构周末申请机构数")
    als_d7_cell_bank_night_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在银行机构夜间申请次数")
    als_d7_cell_bank_night_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在银行机构夜间申请机构数")
    als_d7_cell_nbank_selfnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在本机构(本机构为非银)申请次数")
    als_d7_cell_nbank_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构申请次数")
    als_d7_cell_nbank_p2p_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构-改制机构申请次数")
    als_d7_cell_nbank_mc_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构-小贷机构申请次数")
    als_d7_cell_nbank_ca_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构-现金类分期机构申请次数")
    als_d7_cell_nbank_cf_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构-消费类分期机构申请次数")
    als_d7_cell_nbank_com_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构-代偿类分期机构申请次数")
    als_d7_cell_nbank_oth_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构-其他申请次数")
    als_d7_cell_nbank_nsloan_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构-持牌网络小贷机构申请次数")
    als_d7_cell_nbank_autofin_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构-持牌汽车金融机构申请次数")
    als_d7_cell_nbank_sloan_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构-持牌小贷机构申请次数")
    als_d7_cell_nbank_cons_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构-持牌消费金融机构申请次数")
    als_d7_cell_nbank_finlea_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构-持牌融资租赁机构申请次数")
    als_d7_cell_nbank_else_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构-其他申请次数")
    als_d7_cell_nbank_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构申请机构数")
    als_d7_cell_nbank_p2p_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构-改制机构申请机构数")
    als_d7_cell_nbank_mc_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构-小贷申请机构数")
    als_d7_cell_nbank_ca_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构-现金类分期申请机构数")
    als_d7_cell_nbank_cf_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构-消费类分期申请机构数")
    als_d7_cell_nbank_com_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构-代偿类分期申请机构数")
    als_d7_cell_nbank_oth_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构-其他申请机构数")
    als_d7_cell_nbank_nsloan_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构-持牌网络小贷机构申请机构数")
    als_d7_cell_nbank_autofin_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构-持牌汽车金融机构申请机构数")
    als_d7_cell_nbank_sloan_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构-持牌小贷机构申请机构数")
    als_d7_cell_nbank_cons_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构-持牌消费金融机构申请机构数")
    als_d7_cell_nbank_finlea_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构-持牌融资租赁机构申请机构数")
    als_d7_cell_nbank_else_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构-其他申请机构数")
    als_d7_cell_nbank_week_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构周末申请次数")
    als_d7_cell_nbank_week_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构周末申请机构数")
    als_d7_cell_nbank_night_allnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构夜间申请次数")
    als_d7_cell_nbank_night_orgnum: Optional[str] = Field(None, description="按手机号查询，近 7 天在非银机构夜间申请机构数")

    # 近15天数据 (按身份证号查询)
    als_d15_id_pdl_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天申请线上小额现金贷的次数")
    als_d15_id_pdl_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天申请线上小额现金贷的机构数")
    als_d15_id_caon_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天申请线上现金分期的次数")
    als_d15_id_caon_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天申请线上现金分期的机构数")
    als_d15_id_rel_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天申请信用卡（类信用卡）的次数")
    als_d15_id_rel_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天申请信用卡（类信用卡）的机构数")
    als_d15_id_caoff_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天申请线下现金分期的次数")
    als_d15_id_caoff_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天申请线下现金分期的机构数")
    als_d15_id_cooff_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天申请线下消费分期的次数")
    als_d15_id_cooff_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天申请线下消费分期的机构数")
    als_d15_id_af_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天申请汽车金融的次数")
    als_d15_id_af_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天申请汽车金融的机构数")
    als_d15_id_coon_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天申请线上消费分期的次数")
    als_d15_id_coon_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天申请线上消费分期的机构数")
    als_d15_id_oth_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天申请其他的次数")
    als_d15_id_oth_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天申请其他的机构数")
    als_d15_id_bank_selfnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在本机构(本机构为银行)的申请次数")
    als_d15_id_bank_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在银行机构申请次数")
    als_d15_id_bank_tra_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在银行机构-传统银行申请次数")
    als_d15_id_bank_ret_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在银行机构-网络零售银行申请次数")
    als_d15_id_bank_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在银行机构申请机构数")
    als_d15_id_bank_tra_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在银行机构-传统银行申请机构数")
    als_d15_id_bank_ret_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在银行机构-网络零售银行申请机构数")
    als_d15_id_bank_week_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在银行机构周末申请次数")
    als_d15_id_bank_week_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在银行机构周末申请机构数")
    als_d15_id_bank_night_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在银行机构夜间申请次数")
    als_d15_id_bank_night_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在银行机构夜间申请机构数")
    als_d15_id_nbank_selfnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在本机构(本机构为非银)申请次数")
    als_d15_id_nbank_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构申请次数")
    als_d15_id_nbank_p2p_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构-改制机构申请次数")
    als_d15_id_nbank_mc_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构-小贷机构申请次数")
    als_d15_id_nbank_ca_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构-现金类分期机构申请次数")
    als_d15_id_nbank_cf_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构-消费类分期机构申请次数")
    als_d15_id_nbank_com_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构-代偿类分期机构申请次数")
    als_d15_id_nbank_oth_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构-其他申请次数")
    als_d15_id_nbank_nsloan_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构-持牌网络小贷机构申请次数")
    als_d15_id_nbank_autofin_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构-持牌汽车金融机构申请次数")
    als_d15_id_nbank_sloan_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构-持牌小贷机构申请次数")
    als_d15_id_nbank_cons_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构-持牌消费金融机构申请次数")
    als_d15_id_nbank_finlea_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构-持牌融资租赁机构申请次数")
    als_d15_id_nbank_else_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构-其他申请次数")
    als_d15_id_nbank_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构申请机构数")
    als_d15_id_nbank_p2p_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构-改制机构申请机构数")
    als_d15_id_nbank_mc_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构-小贷申请机构数")
    als_d15_id_nbank_ca_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构-现金类分期申请机构数")
    als_d15_id_nbank_cf_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构-消费类分期申请机构数")
    als_d15_id_nbank_com_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构-代偿类分期申请机构数")
    als_d15_id_nbank_oth_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构-其他申请机构数")
    als_d15_id_nbank_nsloan_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构-持牌网络小贷机构申请机构数")
    als_d15_id_nbank_autofin_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构-持牌汽车金融机构申请机构数")
    als_d15_id_nbank_sloan_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构-持牌小贷机构申请机构数")
    als_d15_id_nbank_cons_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构-持牌消费金融机构申请机构数")
    als_d15_id_nbank_finlea_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构-持牌融资租赁机构申请机构数")
    als_d15_id_nbank_else_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构-其他申请机构数")
    als_d15_id_nbank_week_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构周末申请次数")
    als_d15_id_nbank_week_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构周末申请机构数")
    als_d15_id_nbank_night_allnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构夜间申请次数")
    als_d15_id_nbank_night_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 15 天在非银机构夜间申请机构数")

    # 近15天数据 (按手机号查询)
    als_d15_cell_pdl_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天申请线上小额现金贷的次数")
    als_d15_cell_pdl_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天申请线上小额现金贷的机构数")
    als_d15_cell_caon_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天申请线上现金分期的次数")
    als_d15_cell_caon_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天申请线上现金分期的机构数")
    als_d15_cell_rel_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天申请信用卡（类信用卡）的次数")
    als_d15_cell_rel_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天申请信用卡（类信用卡）的机构数")
    als_d15_cell_caoff_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天申请线下现金分期的次数")
    als_d15_cell_caoff_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天申请线下现金分期的机构数")
    als_d15_cell_cooff_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天申请线下消费分期的次数")
    als_d15_cell_cooff_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天申请线下消费分期的机构数")
    als_d15_cell_af_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天申请汽车金融的次数")
    als_d15_cell_af_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天申请汽车金融的机构数")
    als_d15_cell_coon_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天申请线上消费分期的次数")
    als_d15_cell_coon_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天申请线上消费分期的机构数")
    als_d15_cell_oth_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天申请其他的次数")
    als_d15_cell_oth_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天申请其他的机构数")
    als_d15_cell_bank_selfnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在本机构(本机构为银行)的申请次数")
    als_d15_cell_bank_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在银行机构申请次数")
    als_d15_cell_bank_tra_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在银行机构-传统银行申请次数")
    als_d15_cell_bank_ret_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在银行机构-网络零售银行申请次数")
    als_d15_cell_bank_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在银行机构申请机构数")
    als_d15_cell_bank_tra_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在银行机构-传统银行申请机构数")
    als_d15_cell_bank_ret_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在银行机构-网络零售银行申请机构数")
    als_d15_cell_bank_week_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在银行机构周末申请次数")
    als_d15_cell_bank_week_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在银行机构周末申请机构数")
    als_d15_cell_bank_night_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在银行机构夜间申请次数")
    als_d15_cell_bank_night_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在银行机构夜间申请机构数")
    als_d15_cell_nbank_selfnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在本机构(本机构为非银)申请次数")
    als_d15_cell_nbank_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构申请次数")
    als_d15_cell_nbank_p2p_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构-改制机构申请次数")
    als_d15_cell_nbank_mc_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构-小贷机构申请次数")
    als_d15_cell_nbank_ca_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构-现金类分期机构申请次数")
    als_d15_cell_nbank_cf_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构-消费类分期机构申请次数")
    als_d15_cell_nbank_com_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构-代偿类分期机构申请次数")
    als_d15_cell_nbank_oth_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构-其他申请次数")
    als_d15_cell_nbank_nsloan_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构-持牌网络小贷机构申请次数")
    als_d15_cell_nbank_autofin_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构-持牌汽车金融机构申请次数")
    als_d15_cell_nbank_sloan_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构-持牌小贷机构申请次数")
    als_d15_cell_nbank_cons_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构-持牌消费金融机构申请次数")
    als_d15_cell_nbank_finlea_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构-持牌融资租赁机构申请次数")
    als_d15_cell_nbank_else_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构-其他申请次数")
    als_d15_cell_nbank_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构申请机构数")
    als_d15_cell_nbank_p2p_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构-改制机构申请机构数")
    als_d15_cell_nbank_mc_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构-小贷申请机构数")
    als_d15_cell_nbank_ca_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构-现金类分期申请机构数")
    als_d15_cell_nbank_cf_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构-消费类分期申请机构数")
    als_d15_cell_nbank_com_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构-代偿类分期申请机构数")
    als_d15_cell_nbank_oth_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构-其他申请机构数")
    als_d15_cell_nbank_nsloan_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构-持牌网络小贷机构申请机构数")
    als_d15_cell_nbank_autofin_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构-持牌汽车金融机构申请机构数")
    als_d15_cell_nbank_sloan_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构-持牌小贷机构申请机构数")
    als_d15_cell_nbank_cons_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构-持牌消费金融机构申请机构数")
    als_d15_cell_nbank_finlea_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构-持牌融资租赁机构申请机构数")
    als_d15_cell_nbank_else_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构-其他申请机构数")
    als_d15_cell_nbank_week_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构周末申请次数")
    als_d15_cell_nbank_week_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构周末申请机构数")
    als_d15_cell_nbank_night_allnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构夜间申请次数")
    als_d15_cell_nbank_night_orgnum: Optional[str] = Field(None, description="按手机号查询，近 15 天在非银机构夜间申请机构数")

    # 近1个月数据 (按身份证号查询)
    als_m1_id_pdl_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月申请线上小额现金贷的次数")
    als_m1_id_pdl_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月申请线上小额现金贷的机构数")
    als_m1_id_caon_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月申请线上现金分期的次数")
    als_m1_id_caon_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月申请线上现金分期的机构数")
    als_m1_id_rel_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月申请信用卡（类信用卡）的次数")
    als_m1_id_rel_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月申请信用卡（类信用卡）的机构数")
    als_m1_id_caoff_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月申请线下现金分期的次数")
    als_m1_id_caoff_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月申请线下现金分期的机构数")
    als_m1_id_cooff_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月申请线下消费分期的次数")
    als_m1_id_cooff_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月申请线下消费分期的机构数")
    als_m1_id_af_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月申请汽车金融的次数")
    als_m1_id_af_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月申请汽车金融的机构数")
    als_m1_id_coon_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月申请线上消费分期的次数")
    als_m1_id_coon_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月申请线上消费分期的机构数")
    als_m1_id_oth_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月申请其他的次数")
    als_m1_id_oth_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月申请其他的机构数")
    als_m1_id_bank_selfnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在本机构(本机构为银行)的申请次数")
    als_m1_id_bank_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在银行机构申请次数")
    als_m1_id_bank_tra_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在银行机构-传统银行申请次数")
    als_m1_id_bank_ret_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在银行机构-网络零售银行申请次数")
    als_m1_id_bank_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在银行机构申请机构数")
    als_m1_id_bank_tra_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在银行机构-传统银行申请机构数")
    als_m1_id_bank_ret_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在银行机构-网络零售银行申请机构数")
    als_m1_id_bank_week_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在银行机构周末申请次数")
    als_m1_id_bank_week_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在银行机构周末申请机构数")
    als_m1_id_bank_night_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在银行机构夜间申请次数")
    als_m1_id_bank_night_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在银行机构夜间申请机构数")
    als_m1_id_nbank_selfnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在本机构(本机构为非银)申请次数")
    als_m1_id_nbank_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构申请次数")
    als_m1_id_nbank_p2p_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构-改制机构申请次数")
    als_m1_id_nbank_mc_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构-小贷机构申请次数")
    als_m1_id_nbank_ca_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构-现金类分期机构申请次数")
    als_m1_id_nbank_cf_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构-消费类分期机构申请次数")
    als_m1_id_nbank_com_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构-代偿类分期机构申请次数")
    als_m1_id_nbank_oth_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构-其他申请次数")
    als_m1_id_nbank_nsloan_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构-持牌网络小贷机构申请次数")
    als_m1_id_nbank_autofin_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构-持牌汽车金融机构申请次数")
    als_m1_id_nbank_sloan_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构-持牌小贷机构申请次数")
    als_m1_id_nbank_cons_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构-持牌消费金融机构申请次数")
    als_m1_id_nbank_finlea_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构-持牌融资租赁机构申请次数")
    als_m1_id_nbank_else_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构-其他申请次数")
    als_m1_id_nbank_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构申请机构数")
    als_m1_id_nbank_p2p_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构-改制机构申请机构数")
    als_m1_id_nbank_mc_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构-小贷申请机构数")
    als_m1_id_nbank_ca_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构-现金类分期申请机构数")
    als_m1_id_nbank_cf_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构-消费类分期申请机构数")
    als_m1_id_nbank_com_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构-代偿类分期申请机构数")
    als_m1_id_nbank_oth_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构-其他申请机构数")
    als_m1_id_nbank_nsloan_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构-持牌网络小贷机构申请机构数")
    als_m1_id_nbank_autofin_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构-持牌汽车金融机构申请机构数")
    als_m1_id_nbank_sloan_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构-持牌小贷机构申请机构数")
    als_m1_id_nbank_cons_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构-持牌消费金融机构申请机构数")
    als_m1_id_nbank_finlea_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构-持牌融资租赁机构申请机构数")
    als_m1_id_nbank_else_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构-其他申请机构数")
    als_m1_id_nbank_week_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构周末申请次数")
    als_m1_id_nbank_week_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构周末申请机构数")
    als_m1_id_nbank_night_allnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构夜间申请次数")
    als_m1_id_nbank_night_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 1 个月在非银机构夜间申请机构数")

    # 近1个月数据 (按手机号查询)
    als_m1_cell_pdl_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月申请线上小额现金贷的次数")
    als_m1_cell_pdl_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月申请线上小额现金贷的机构数")
    als_m1_cell_caon_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月申请线上现金分期的次数")
    als_m1_cell_caon_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月申请线上现金分期的机构数")
    als_m1_cell_rel_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月申请信用卡（类信用卡）的次数")
    als_m1_cell_rel_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月申请信用卡（类信用卡）的机构数")
    als_m1_cell_caoff_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月申请线下现金分期的次数")
    als_m1_cell_caoff_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月申请线下现金分期的机构数")
    als_m1_cell_cooff_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月申请线下消费分期的次数")
    als_m1_cell_cooff_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月申请线下消费分期的机构数")
    als_m1_cell_af_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月申请汽车金融的次数")
    als_m1_cell_af_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月申请汽车金融的机构数")
    als_m1_cell_coon_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月申请线上消费分期的次数")
    als_m1_cell_coon_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月申请线上消费分期的机构数")
    als_m1_cell_oth_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月申请其他的次数")
    als_m1_cell_oth_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月申请其他的机构数")
    als_m1_cell_bank_selfnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在本机构(本机构为银行)的申请次数")
    als_m1_cell_bank_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在银行机构申请次数")
    als_m1_cell_bank_tra_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在银行机构-传统银行申请次数")
    als_m1_cell_bank_ret_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在银行机构-网络零售银行申请次数")
    als_m1_cell_bank_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在银行机构申请机构数")
    als_m1_cell_bank_tra_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在银行机构-传统银行申请机构数")
    als_m1_cell_bank_ret_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在银行机构-网络零售银行申请机构数")
    als_m1_cell_bank_week_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在银行机构周末申请次数")
    als_m1_cell_bank_week_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在银行机构周末申请机构数")
    als_m1_cell_bank_night_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在银行机构夜间申请次数")
    als_m1_cell_bank_night_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在银行机构夜间申请机构数")
    als_m1_cell_nbank_selfnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在本机构(本机构为非银)申请次数")
    als_m1_cell_nbank_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构申请次数")
    als_m1_cell_nbank_p2p_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构-改制机构申请次数")
    als_m1_cell_nbank_mc_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构-小贷机构申请次数")
    als_m1_cell_nbank_ca_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构-现金类分期机构申请次数")
    als_m1_cell_nbank_cf_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构-消费类分期机构申请次数")
    als_m1_cell_nbank_com_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构-代偿类分期机构申请次数")
    als_m1_cell_nbank_oth_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构-其他申请次数")
    als_m1_cell_nbank_nsloan_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构-持牌网络小贷机构申请次数")
    als_m1_cell_nbank_autofin_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构-持牌汽车金融机构申请次数")
    als_m1_cell_nbank_sloan_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构-持牌小贷机构申请次数")
    als_m1_cell_nbank_cons_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构-持牌消费金融机构申请次数")
    als_m1_cell_nbank_finlea_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构-持牌融资租赁机构申请次数")
    als_m1_cell_nbank_else_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构-其他申请次数")
    als_m1_cell_nbank_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构申请机构数")
    als_m1_cell_nbank_p2p_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构-改制机构申请机构数")
    als_m1_cell_nbank_mc_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构-小贷申请机构数")
    als_m1_cell_nbank_ca_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构-现金类分期申请机构数")
    als_m1_cell_nbank_cf_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构-消费类分期申请机构数")
    als_m1_cell_nbank_com_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构-代偿类分期申请机构数")
    als_m1_cell_nbank_oth_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构-其他申请机构数")
    als_m1_cell_nbank_nsloan_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构-持牌网络小贷机构申请机构数")
    als_m1_cell_nbank_autofin_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构-持牌汽车金融机构申请机构数")
    als_m1_cell_nbank_sloan_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构-持牌小贷机构申请机构数")
    als_m1_cell_nbank_cons_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构-持牌消费金融机构申请机构数")
    als_m1_cell_nbank_finlea_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构-持牌融资租赁机构申请机构数")
    als_m1_cell_nbank_else_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构-其他申请机构数")
    als_m1_cell_nbank_week_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构周末申请次数")
    als_m1_cell_nbank_week_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构周末申请机构数")
    als_m1_cell_nbank_night_allnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构夜间申请次数")
    als_m1_cell_nbank_night_orgnum: Optional[str] = Field(None, description="按手机号查询，近 1 个月在非银机构夜间申请机构数")

    # 近3个月数据 (按身份证号查询)
    als_m3_id_max_inteday: Optional[str] = Field(None, description="按身份证号查询，距最早在银行机构申请的间隔天数")
    als_m3_id_min_inteday: Optional[str] = Field(None, description="按身份证号查询，距最早在非银行机构申请的间隔天数")
    als_m3_id_tot_mons: Optional[str] = Field(None, description="按身份证号查询，近 3 个月有申请记录月份数")
    als_m3_id_avg_monnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月平均每月申请次数 (有申请月份平均)")
    als_m3_id_max_monnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月最大月申请次数")
    als_m3_id_min_monnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月最小月申请次数")
    als_m3_id_pdl_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月申请线上小额现金贷的次数")
    als_m3_id_pdl_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月申请线上小额现金贷的机构数")
    als_m3_id_caon_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月申请线上现金分期的次数")
    als_m3_id_caon_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月申请线上现金分期的机构数")
    als_m3_id_rel_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月申请信用卡（类信用卡）的次数")
    als_m3_id_rel_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月申请信用卡（类信用卡）的机构数")
    als_m3_id_caoff_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月申请线下现金分期的次数")
    als_m3_id_caoff_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月申请线下现金分期的机构数")
    als_m3_id_cooff_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月申请线下消费分期的次数")
    als_m3_id_cooff_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月申请线下消费分期的机构数")
    als_m3_id_af_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月申请汽车金融的次数")
    als_m3_id_af_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月申请汽车金融的机构数")
    als_m3_id_coon_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月申请线上消费分期的次数")
    als_m3_id_coon_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月申请线上消费分期的机构数")
    als_m3_id_oth_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月申请其他的次数")
    als_m3_id_oth_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月申请其他的机构数")
    als_m3_id_bank_selfnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在本机构(本机构为银行)的申请次数")
    als_m3_id_bank_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在银行机构申请次数")
    als_m3_id_bank_tra_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在银行机构-传统银行申请次数")
    als_m3_id_bank_ret_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在银行机构-网络零售银行申请次数")
    als_m3_id_bank_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在银行机构申请机构数")
    als_m3_id_bank_tra_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在银行机构-传统银行申请机构数")
    als_m3_id_bank_ret_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在银行机构-网络零售银行申请机构数")
    als_m3_id_bank_tot_mons: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在银行机构有申请记录月份数")
    als_m3_id_bank_avg_monnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在银行机构平均每月申请次数 (有申请月份平均)")
    als_m3_id_bank_max_monnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在银行机构最大月申请次数")
    als_m3_id_bank_min_monnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在银行机构最小月申请次数")
    als_m3_id_bank_max_inteday: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在银行机构申请最大间隔天数")
    als_m3_id_bank_min_inteday: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在银行机构申请最小间隔天数")
    als_m3_id_bank_week_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在银行机构周末申请次数")
    als_m3_id_bank_week_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在银行机构周末申请机构数")
    als_m3_id_bank_night_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在银行机构夜间申请次数")
    als_m3_id_bank_night_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在银行机构夜间申请机构数")
    als_m3_id_nbank_selfnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在本机构(本机构为非银)申请次数")
    als_m3_id_nbank_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构申请次数")
    als_m3_id_nbank_p2p_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构-改制机构申请次数")
    als_m3_id_nbank_mc_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构-小贷机构申请次数")
    als_m3_id_nbank_ca_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构-现金类分期机构申请次数")
    als_m3_id_nbank_cf_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构-消费类分期机构申请次数")
    als_m3_id_nbank_com_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构-代偿类分期机构申请次数")
    als_m3_id_nbank_oth_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构-其他申请次数")
    als_m3_id_nbank_nsloan_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构-持牌网络小贷机构申请次数")
    als_m3_id_nbank_autofin_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构-持牌汽车金融机构申请次数")
    als_m3_id_nbank_sloan_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构-持牌小贷机构申请次数")
    als_m3_id_nbank_cons_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构-持牌消费金融机构申请次数")
    als_m3_id_nbank_finlea_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构-持牌融资租赁机构申请次数")
    als_m3_id_nbank_else_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构-其他申请次数")
    als_m3_id_nbank_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构申请机构数")
    als_m3_id_nbank_p2p_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构-改制机构申请机构数")
    als_m3_id_nbank_mc_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构-小贷申请机构数")
    als_m3_id_nbank_ca_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构-现金类分期申请机构数")
    als_m3_id_nbank_cf_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构-消费类分期申请机构数")
    als_m3_id_nbank_com_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构-代偿类分期申请机构数")
    als_m3_id_nbank_oth_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构-其他申请机构数")
    als_m3_id_nbank_nsloan_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构-持牌网络小贷机构申请机构数")
    als_m3_id_nbank_autofin_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构-持牌汽车金融机构申请机构数")
    als_m3_id_nbank_sloan_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构-持牌小贷机构申请机构数")
    als_m3_id_nbank_cons_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构-持牌消费金融机构申请机构数")
    als_m3_id_nbank_finlea_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构-持牌融资租赁机构申请机构数")
    als_m3_id_nbank_else_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构-其他申请机构数")
    als_m3_id_nbank_tot_mons: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构有申请记录月份数")
    als_m3_id_nbank_avg_monnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构平均每月申请次数 (有申请月份平均)")
    als_m3_id_nbank_max_monnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构最大月申请次数")
    als_m3_id_nbank_min_monnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构最小月申请次数")
    als_m3_id_nbank_max_inteday: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构申请最大间隔天数")
    als_m3_id_nbank_min_inteday: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构申请最小间隔天数")
    als_m3_id_nbank_week_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构周末申请次数")
    als_m3_id_nbank_week_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构周末申请机构数")
    als_m3_id_nbank_night_allnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构夜间申请次数")
    als_m3_id_nbank_night_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 3 个月在非银机构夜间申请机构数")

    # 近3个月数据 (按手机号查询)
    als_m3_cell_max_inteday: Optional[str] = Field(None, description="按手机号查询，距最早在银行机构申请的间隔天数")
    als_m3_cell_min_inteday: Optional[str] = Field(None, description="按手机号查询，距最早在非银行机构申请的间隔天数")
    als_m3_cell_tot_mons: Optional[str] = Field(None, description="按手机号查询，近 3 个月有申请记录月份数")
    als_m3_cell_avg_monnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月平均每月申请次数 (有申请月份平均)")
    als_m3_cell_max_monnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月最大月申请次数")
    als_m3_cell_min_monnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月最小月申请次数")
    als_m3_cell_pdl_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月申请线上小额现金贷的次数")
    als_m3_cell_pdl_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月申请线上小额现金贷的机构数")
    als_m3_cell_caon_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月申请线上现金分期的次数")
    als_m3_cell_caon_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月申请线上现金分期的机构数")
    als_m3_cell_rel_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月申请信用卡（类信用卡）的次数")
    als_m3_cell_rel_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月申请信用卡（类信用卡）的机构数")
    als_m3_cell_caoff_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月申请线下现金分期的次数")
    als_m3_cell_caoff_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月申请线下现金分期的机构数")
    als_m3_cell_cooff_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月申请线下消费分期的次数")
    als_m3_cell_cooff_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月申请线下消费分期的机构数")
    als_m3_cell_af_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月申请汽车金融的次数")
    als_m3_cell_af_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月申请汽车金融的机构数")
    als_m3_cell_coon_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月申请线上消费分期的次数")
    als_m3_cell_coon_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月申请线上消费分期的机构数")
    als_m3_cell_oth_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月申请其他的次数")
    als_m3_cell_oth_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月申请其他的机构数")
    als_m3_cell_bank_selfnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在本机构(本机构为银行)的申请次数")
    als_m3_cell_bank_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在银行机构申请次数")
    als_m3_cell_bank_tra_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在银行机构-传统银行申请次数")
    als_m3_cell_bank_ret_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在银行机构-网络零售银行申请次数")
    als_m3_cell_bank_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在银行机构申请机构数")
    als_m3_cell_bank_tra_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在银行机构-传统银行申请机构数")
    als_m3_cell_bank_ret_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在银行机构-网络零售银行申请机构数")
    als_m3_cell_bank_tot_mons: Optional[str] = Field(None, description="按手机号查询，近 3 个月在银行机构有申请记录月份数")
    als_m3_cell_bank_avg_monnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在银行机构平均每月申请次数 (有申请月份平均)")
    als_m3_cell_bank_max_monnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在银行机构最大月申请次数")
    als_m3_cell_bank_min_monnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在银行机构最小月申请次数")
    als_m3_cell_bank_max_inteday: Optional[str] = Field(None, description="按手机号查询，近 3 个月在银行机构申请最大间隔天数")
    als_m3_cell_bank_min_inteday: Optional[str] = Field(None, description="按手机号查询，近 3 个月在银行机构申请最小间隔天数")
    als_m3_cell_bank_week_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在银行机构周末申请次数")
    als_m3_cell_bank_week_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在银行机构周末申请机构数")
    als_m3_cell_bank_night_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在银行机构夜间申请次数")
    als_m3_cell_bank_night_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在银行机构夜间申请机构数")
    als_m3_cell_nbank_selfnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在本机构(本机构为非银)申请次数")
    als_m3_cell_nbank_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构申请次数")
    als_m3_cell_nbank_p2p_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构-改制机构申请次数")
    als_m3_cell_nbank_mc_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构-小贷机构申请次数")
    als_m3_cell_nbank_ca_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构-现金类分期机构申请次数")
    als_m3_cell_nbank_cf_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构-消费类分期机构申请次数")
    als_m3_cell_nbank_com_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构-代偿类分期机构申请次数")
    als_m3_cell_nbank_oth_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构-其他申请次数")
    als_m3_cell_nbank_nsloan_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构-持牌网络小贷机构申请次数")
    als_m3_cell_nbank_autofin_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构-持牌汽车金融机构申请次数")
    als_m3_cell_nbank_sloan_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构-持牌小贷机构申请次数")
    als_m3_cell_nbank_cons_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构-持牌消费金融机构申请次数")
    als_m3_cell_nbank_finlea_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构-持牌融资租赁机构申请次数")
    als_m3_cell_nbank_else_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构-其他申请次数")
    als_m3_cell_nbank_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构申请机构数")
    als_m3_cell_nbank_p2p_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构-改制机构申请机构数")
    als_m3_cell_nbank_mc_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构-小贷申请机构数")
    als_m3_cell_nbank_ca_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构-现金类分期申请机构数")
    als_m3_cell_nbank_cf_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构-消费类分期申请机构数")
    als_m3_cell_nbank_com_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构-代偿类分期申请机构数")
    als_m3_cell_nbank_oth_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构-其他申请机构数")
    als_m3_cell_nbank_nsloan_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构-持牌网络小贷机构申请机构数")
    als_m3_cell_nbank_autofin_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构-持牌汽车金融机构申请机构数")
    als_m3_cell_nbank_sloan_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构-持牌小贷机构申请机构数")
    als_m3_cell_nbank_cons_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构-持牌消费金融机构申请机构数")
    als_m3_cell_nbank_finlea_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构-持牌融资租赁机构申请机构数")
    als_m3_cell_nbank_else_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构-其他申请机构数")
    als_m3_cell_nbank_tot_mons: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构有申请记录月份数")
    als_m3_cell_nbank_avg_monnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构平均每月申请次数 (有申请月份平均)")
    als_m3_cell_nbank_max_monnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构最大月申请次数")
    als_m3_cell_nbank_min_monnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构最小月申请次数")
    als_m3_cell_nbank_max_inteday: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构申请最大间隔天数")
    als_m3_cell_nbank_min_inteday: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构申请最小间隔天数")
    als_m3_cell_nbank_week_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构周末申请次数")
    als_m3_cell_nbank_week_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构周末申请机构数")
    als_m3_cell_nbank_night_allnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构夜间申请次数")
    als_m3_cell_nbank_night_orgnum: Optional[str] = Field(None, description="按手机号查询，近 3 个月在非银机构夜间申请机构数")

    # 近6个月数据 (按身份证号查询)
    als_m6_id_max_inteday: Optional[str] = Field(None, description="按身份证号查询，距最早在银行机构申请的间隔天数")
    als_m6_id_min_inteday: Optional[str] = Field(None, description="按身份证号查询，距最早在非银行机构申请的间隔天数")
    als_m6_id_tot_mons: Optional[str] = Field(None, description="按身份证号查询，近 6 个月有申请记录月份数")
    als_m6_id_avg_monnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月平均每月申请次数 (有申请月份平均)")
    als_m6_id_max_monnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月最大月申请次数")
    als_m6_id_min_monnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月最小月申请次数")
    als_m6_id_pdl_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月申请线上小额现金贷的次数")
    als_m6_id_pdl_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月申请线上小额现金贷的机构数")
    als_m6_id_caon_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月申请线上现金分期的次数")
    als_m6_id_caon_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月申请线上现金分期的机构数")
    als_m6_id_rel_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月申请信用卡（类信用卡）的次数")
    als_m6_id_rel_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月申请信用卡（类信用卡）的机构数")
    als_m6_id_caoff_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月申请线下现金分期的次数")
    als_m6_id_caoff_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月申请线下现金分期的机构数")
    als_m6_id_cooff_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月申请线下消费分期的次数")
    als_m6_id_cooff_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月申请线下消费分期的机构数")
    als_m6_id_af_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月申请汽车金融的次数")
    als_m6_id_af_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月申请汽车金融的机构数")
    als_m6_id_coon_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月申请线上消费分期的次数")
    als_m6_id_coon_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月申请线上消费分期的机构数")
    als_m6_id_oth_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月申请其他的次数")
    als_m6_id_oth_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月申请其他的机构数")
    als_m6_id_bank_selfnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在本机构(本机构为银行)的申请次数")
    als_m6_id_bank_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在银行机构申请次数")
    als_m6_id_bank_tra_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在银行机构-传统银行申请次数")
    als_m6_id_bank_ret_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在银行机构-网络零售银行申请次数")
    als_m6_id_bank_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在银行机构申请机构数")
    als_m6_id_bank_tra_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在银行机构-传统银行申请机构数")
    als_m6_id_bank_ret_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在银行机构-网络零售银行申请机构数")
    als_m6_id_bank_tot_mons: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在银行机构有申请记录月份数")
    als_m6_id_bank_avg_monnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在银行机构平均每月申请次数 (有申请月份平均)")
    als_m6_id_bank_max_monnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在银行机构最大月申请次数")
    als_m6_id_bank_min_monnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在银行机构最小月申请次数")
    als_m6_id_bank_max_inteday: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在银行机构申请最大间隔天数")
    als_m6_id_bank_min_inteday: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在银行机构申请最小间隔天数")
    als_m6_id_bank_week_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在银行机构周末申请次数")
    als_m6_id_bank_week_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在银行机构周末申请机构数")
    als_m6_id_bank_night_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在银行机构夜间申请次数")
    als_m6_id_bank_night_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在银行机构夜间申请机构数")
    als_m6_id_nbank_selfnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在本机构(本机构为非银)申请次数")
    als_m6_id_nbank_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构申请次数")
    als_m6_id_nbank_p2p_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构-改制机构申请次数")
    als_m6_id_nbank_mc_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构-小贷机构申请次数")
    als_m6_id_nbank_ca_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构-现金类分期机构申请次数")
    als_m6_id_nbank_cf_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构-消费类分期机构申请次数")
    als_m6_id_nbank_com_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构-代偿类分期机构申请次数")
    als_m6_id_nbank_oth_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构-其他申请次数")
    als_m6_id_nbank_nsloan_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构-持牌网络小贷机构申请次数")
    als_m6_id_nbank_autofin_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构-持牌汽车金融机构申请次数")
    als_m6_id_nbank_sloan_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构-持牌小贷机构申请次数")
    als_m6_id_nbank_cons_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构-持牌消费金融机构申请次数")
    als_m6_id_nbank_finlea_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构-持牌融资租赁机构申请次数")
    als_m6_id_nbank_else_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构-其他申请次数")
    als_m6_id_nbank_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构申请机构数")
    als_m6_id_nbank_p2p_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构-改制机构申请机构数")
    als_m6_id_nbank_mc_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构-小贷申请机构数")
    als_m6_id_nbank_ca_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构-现金类分期申请机构数")
    als_m6_id_nbank_cf_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构-消费类分期申请机构数")
    als_m6_id_nbank_com_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构-代偿类分期申请机构数")
    als_m6_id_nbank_oth_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构-其他申请机构数")
    als_m6_id_nbank_nsloan_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构-持牌网络小贷机构申请机构数")
    als_m6_id_nbank_autofin_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构-持牌汽车金融机构申请机构数")
    als_m6_id_nbank_sloan_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构-持牌小贷机构申请机构数")
    als_m6_id_nbank_cons_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构-持牌消费金融机构申请机构数")
    als_m6_id_nbank_finlea_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构-持牌融资租赁机构申请机构数")
    als_m6_id_nbank_else_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构-其他申请机构数")
    als_m6_id_nbank_tot_mons: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构有申请记录月份数")
    als_m6_id_nbank_avg_monnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构平均每月申请次数 (有申请月份平均)")
    als_m6_id_nbank_max_monnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构最大月申请次数")
    als_m6_id_nbank_min_monnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构最小月申请次数")
    als_m6_id_nbank_max_inteday: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构申请最大间隔天数")
    als_m6_id_nbank_min_inteday: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构申请最小间隔天数")
    als_m6_id_nbank_week_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构周末申请次数")
    als_m6_id_nbank_week_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构周末申请机构数")
    als_m6_id_nbank_night_allnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构夜间申请次数")
    als_m6_id_nbank_night_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 6 个月在非银机构夜间申请机构数")

    # 近6个月数据 (按手机号查询)
    als_m6_cell_max_inteday: Optional[str] = Field(None, description="按手机号查询，距最早在银行机构申请的间隔天数")
    als_m6_cell_min_inteday: Optional[str] = Field(None, description="按手机号查询，距最早在非银行机构申请的间隔天数")
    als_m6_cell_tot_mons: Optional[str] = Field(None, description="按手机号查询，近 6 个月有申请记录月份数")
    als_m6_cell_avg_monnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构平均每月申请次数 (有申请月份平均)")
    als_m6_cell_max_monnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构最大月申请次数")
    als_m6_cell_min_monnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构最小月申请次数")
    als_m6_cell_pdl_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月申请线上小额现金贷的次数")
    als_m6_cell_pdl_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月申请线上小额现金贷的机构数")
    als_m6_cell_caon_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月申请线上现金分期的次数")
    als_m6_cell_caon_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月申请线上现金分期的机构数")
    als_m6_cell_rel_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月申请信用卡（类信用卡）的次数")
    als_m6_cell_rel_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月申请信用卡（类信用卡）的机构数")
    als_m6_cell_caoff_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月申请线下现金分期的次数")
    als_m6_cell_caoff_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月申请线下现金分期的机构数")
    als_m6_cell_cooff_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月申请线下消费分期的次数")
    als_m6_cell_cooff_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月申请线下消费分期的机构数")
    als_m6_cell_af_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月申请汽车金融的次数")
    als_m6_cell_af_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月申请汽车金融的机构数")
    als_m6_cell_coon_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月申请线上消费分期的次数")
    als_m6_cell_coon_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月申请线上消费分期的机构数")
    als_m6_cell_oth_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月申请其他的次数")
    als_m6_cell_oth_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月申请其他的机构数")
    als_m6_cell_bank_selfnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在本机构(本机构为银行)的申请次数")
    als_m6_cell_bank_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在银行机构申请次数")
    als_m6_cell_bank_tra_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在银行机构-传统银行申请次数")
    als_m6_cell_bank_ret_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在银行机构-网络零售银行申请次数")
    als_m6_cell_bank_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在银行机构申请机构数")
    als_m6_cell_bank_tra_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在银行机构-传统银行申请机构数")
    als_m6_cell_bank_ret_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在银行机构-网络零售银行申请机构数")
    als_m6_cell_bank_tot_mons: Optional[str] = Field(None, description="按手机号查询，近 6 个月在银行机构有申请记录月份数")
    als_m6_cell_bank_avg_monnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在银行机构平均每月申请次数 (有申请月份平均)")
    als_m6_cell_bank_max_monnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在银行机构最大月申请次数")
    als_m6_cell_bank_min_monnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在银行机构最小月申请次数")
    als_m6_cell_bank_max_inteday: Optional[str] = Field(None, description="按手机号查询，近 6 个月在银行机构申请最大间隔天数")
    als_m6_cell_bank_min_inteday: Optional[str] = Field(None, description="按手机号查询，近 6 个月在银行机构申请最小间隔天数")
    als_m6_cell_bank_week_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在银行机构周末申请次数")
    als_m6_cell_bank_week_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在银行机构周末申请机构数")
    als_m6_cell_bank_night_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在银行机构夜间申请次数")
    als_m6_cell_bank_night_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在银行机构夜间申请机构数")
    als_m6_cell_nbank_selfnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在本机构(本机构为非银)申请次数")
    als_m6_cell_nbank_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构申请次数")
    als_m6_cell_nbank_p2p_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构-改制机构申请次数")
    als_m6_cell_nbank_mc_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构-小贷机构申请次数")
    als_m6_cell_nbank_ca_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构-现金类分期机构申请次数")
    als_m6_cell_nbank_cf_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构-消费类分期机构申请次数")
    als_m6_cell_nbank_com_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构-代偿类分期机构申请次数")
    als_m6_cell_nbank_oth_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构-其他申请次数")
    als_m6_cell_nbank_nsloan_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构-持牌网络小贷机构申请次数")
    als_m6_cell_nbank_autofin_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构-持牌汽车金融机构申请次数")
    als_m6_cell_nbank_sloan_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构-持牌小贷机构申请次数")
    als_m6_cell_nbank_cons_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构-持牌消费金融机构申请次数")
    als_m6_cell_nbank_finlea_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构-持牌融资租赁机构申请次数")
    als_m6_cell_nbank_else_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构-其他申请次数")
    als_m6_cell_nbank_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构申请机构数")
    als_m6_cell_nbank_p2p_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构-改制机构申请机构数")
    als_m6_cell_nbank_mc_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构-小贷申请机构数")
    als_m6_cell_nbank_ca_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构-现金类分期申请机构数")
    als_m6_cell_nbank_cf_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构-消费类分期申请机构数")
    als_m6_cell_nbank_com_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构-代偿类分期申请机构数")
    als_m6_cell_nbank_oth_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构-其他申请机构数")
    als_m6_cell_nbank_nsloan_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构-持牌网络小贷机构申请机构数")
    als_m6_cell_nbank_autofin_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构-持牌汽车金融机构申请机构数")
    als_m6_cell_nbank_sloan_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构-持牌小贷机构申请机构数")
    als_m6_cell_nbank_cons_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构-持牌消费金融机构申请机构数")
    als_m6_cell_nbank_finlea_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构-持牌融资租赁机构申请机构数")
    als_m6_cell_nbank_else_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构-其他申请机构数")
    als_m6_cell_nbank_tot_mons: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构有申请记录月份数")
    als_m6_cell_nbank_avg_monnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构平均每月申请次数 (有申请月份平均)")
    als_m6_cell_nbank_max_monnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构最大月申请次数")
    als_m6_cell_nbank_min_monnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构最小月申请次数")
    als_m6_cell_nbank_max_inteday: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构申请最大间隔天数")
    als_m6_cell_nbank_min_inteday: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构申请最小间隔天数")
    als_m6_cell_nbank_week_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构周末申请次数")
    als_m6_cell_nbank_week_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构周末申请机构数")
    als_m6_cell_nbank_night_allnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构夜间申请次数")
    als_m6_cell_nbank_night_orgnum: Optional[str] = Field(None, description="按手机号查询，近 6 个月在非银机构夜间申请机构数")

    # 近12个月数据 (按身份证号查询)
    als_m12_id_max_inteday: Optional[str] = Field(None, description="按身份证号查询，距最早在银行机构申请的间隔天数")
    als_m12_id_min_inteday: Optional[str] = Field(None, description="按身份证号查询，距最早在非银行机构申请的间隔天数")
    als_m12_id_tot_mons: Optional[str] = Field(None, description="按身份证号查询，近 12 个月有申请记录月份数")
    als_m12_id_avg_monnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月平均每月申请次数 (有申请月份平均)")
    als_m12_id_max_monnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月最大月申请次数")
    als_m12_id_min_monnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月最小月申请次数")
    als_m12_id_pdl_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月申请线上小额现金贷的次数")
    als_m12_id_pdl_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月申请线上小额现金贷的机构数")
    als_m12_id_caon_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月申请线上现金分期的次数")
    als_m12_id_caon_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月申请线上现金分期的机构数")
    als_m12_id_rel_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月申请信用卡（类信用卡）的次数")
    als_m12_id_rel_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月申请信用卡（类信用卡）的机构数")
    als_m12_id_caoff_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月申请线下现金分期的次数")
    als_m12_id_caoff_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月申请线下现金分期的机构数")
    als_m12_id_cooff_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月申请线下消费分期的次数")
    als_m12_id_cooff_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月申请线下消费分期的机构数")
    als_m12_id_af_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月申请汽车金融的次数")
    als_m12_id_af_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月申请汽车金融的机构数")
    als_m12_id_coon_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月申请线上消费分期的次数")
    als_m12_id_coon_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月申请线上消费分期的机构数")
    als_m12_id_oth_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月申请其他的次数")
    als_m12_id_oth_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月申请其他的机构数")
    als_m12_id_bank_selfnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在本机构(本机构为银行)的申请次数")
    als_m12_id_bank_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在银行机构申请次数")
    als_m12_id_bank_tra_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在银行机构-传统银行申请次数")
    als_m12_id_bank_ret_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在银行机构-网络零售银行申请次数")
    als_m12_id_bank_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在银行机构申请机构数")
    als_m12_id_bank_tra_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在银行机构-传统银行申请机构数")
    als_m12_id_bank_ret_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在银行机构-网络零售银行申请机构数")
    als_m12_id_bank_tot_mons: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在银行机构有申请记录月份数")
    als_m12_id_bank_avg_monnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在银行机构平均每月申请次数 (有申请月份平均)")
    als_m12_id_bank_max_monnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在银行机构最大月申请次数")
    als_m12_id_bank_min_monnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在银行机构最小月申请次数")
    als_m12_id_bank_max_inteday: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在银行机构申请最大间隔天数")
    als_m12_id_bank_min_inteday: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在银行机构申请最小间隔天数")
    als_m12_id_bank_week_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在银行机构周末申请次数")
    als_m12_id_bank_week_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在银行机构周末申请机构数")
    als_m12_id_bank_night_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在银行机构夜间申请次数")
    als_m12_id_bank_night_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在银行机构夜间申请机构数")
    als_m12_id_nbank_selfnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在本机构(本机构为非银)申请次数")
    als_m12_id_nbank_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构申请次数")
    als_m12_id_nbank_p2p_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构-改制机构申请次数")
    als_m12_id_nbank_mc_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构-小贷机构申请次数")
    als_m12_id_nbank_ca_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构-现金类分期机构申请次数")
    als_m12_id_nbank_cf_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构-消费类分期机构申请次数")
    als_m12_id_nbank_com_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构-代偿类分期机构申请次数")
    als_m12_id_nbank_oth_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构-其他申请次数")
    als_m12_id_nbank_nsloan_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构-持牌网络小贷机构申请次数")
    als_m12_id_nbank_autofin_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构-持牌汽车金融机构申请次数")
    als_m12_id_nbank_sloan_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构-持牌小贷机构申请次数")
    als_m12_id_nbank_cons_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构-持牌消费金融机构申请次数")
    als_m12_id_nbank_finlea_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构-持牌融资租赁机构申请次数")
    als_m12_id_nbank_else_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构-其他申请次数")
    als_m12_id_nbank_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构申请机构数")
    als_m12_id_nbank_p2p_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构-改制机构申请机构数")
    als_m12_id_nbank_mc_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构-小贷申请机构数")
    als_m12_id_nbank_ca_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构-现金类分期申请机构数")
    als_m12_id_nbank_cf_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构-消费类分期申请机构数")
    als_m12_id_nbank_com_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构-代偿类分期申请机构数")
    als_m12_id_nbank_oth_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构-其他申请机构数")
    als_m12_id_nbank_nsloan_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构-持牌网络小贷机构申请机构数")
    als_m12_id_nbank_autofin_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构-持牌汽车金融机构申请机构数")
    als_m12_id_nbank_sloan_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构-持牌小贷机构申请机构数")
    als_m12_id_nbank_cons_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构-持牌消费金融机构申请机构数")
    als_m12_id_nbank_finlea_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构-持牌融资租赁机构申请机构数")
    als_m12_id_nbank_else_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构-其他申请机构数")
    als_m12_id_nbank_tot_mons: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构有申请记录月份数")
    als_m12_id_nbank_avg_monnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构平均每月申请次数 (有申请月份平均)")
    als_m12_id_nbank_max_monnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构最大月申请次数")
    als_m12_id_nbank_min_monnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构最小月申请次数")
    als_m12_id_nbank_max_inteday: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构申请最大间隔天数")
    als_m12_id_nbank_min_inteday: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构申请最小间隔天数")
    als_m12_id_nbank_week_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构周末申请次数")
    als_m12_id_nbank_week_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构周末申请机构数")
    als_m12_id_nbank_night_allnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构夜间申请次数")
    als_m12_id_nbank_night_orgnum: Optional[str] = Field(None, description="按身份证号查询，近 12 个月在非银机构夜间申请机构数")

    # 近12个月数据 (按手机号查询)
    als_m12_cell_max_inteday: Optional[str] = Field(None, description="按手机号查询，距最早在银行机构申请的间隔天数")
    als_m12_cell_min_inteday: Optional[str] = Field(None, description="按手机号查询，距最早在非银行机构申请的间隔天数")
    als_m12_cell_tot_mons: Optional[str] = Field(None, description="按手机号查询，近 12 个月有申请记录月份数")
    als_m12_cell_avg_monnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构平均每月申请次数 (有申请月份平均)")
    als_m12_cell_max_monnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构最大月申请次数")
    als_m12_cell_min_monnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构最小月申请次数")
    als_m12_cell_pdl_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月申请线上小额现金贷的次数")
    als_m12_cell_pdl_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月申请线上小额现金贷的机构数")
    als_m12_cell_caon_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月申请线上现金分期的次数")
    als_m12_cell_caon_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月申请线上现金分期的机构数")
    als_m12_cell_rel_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月申请信用卡（类信用卡）的次数")
    als_m12_cell_rel_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月申请信用卡（类信用卡）的机构数")
    als_m12_cell_caoff_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月申请线下现金分期的次数")
    als_m12_cell_caoff_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月申请线下现金分期的机构数")
    als_m12_cell_cooff_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月申请线下消费分期的次数")
    als_m12_cell_cooff_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月申请线下消费分期的机构数")
    als_m12_cell_af_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月申请汽车金融的次数")
    als_m12_cell_af_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月申请汽车金融的机构数")
    als_m12_cell_coon_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月申请线上消费分期的次数")
    als_m12_cell_coon_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月申请线上消费分期的机构数")
    als_m12_cell_oth_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月申请其他的次数")
    als_m12_cell_oth_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月申请其他的机构数")
    als_m12_cell_bank_selfnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在本机构(本机构为银行)的申请次数")
    als_m12_cell_bank_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在银行机构申请次数")
    als_m12_cell_bank_tra_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在银行机构-传统银行申请次数")
    als_m12_cell_bank_ret_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在银行机构-网络零售银行申请次数")
    als_m12_cell_bank_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在银行机构申请机构数")
    als_m12_cell_bank_tra_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在银行机构-传统银行申请机构数")
    als_m12_cell_bank_ret_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在银行机构-网络零售银行申请机构数")
    als_m12_cell_bank_tot_mons: Optional[str] = Field(None, description="按手机号查询，近 12 个月在银行机构有申请记录月份数")
    als_m12_cell_bank_avg_monnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在银行机构平均每月申请次数 (有申请月份平均)")
    als_m12_cell_bank_max_monnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在银行机构最大月申请次数")
    als_m12_cell_bank_min_monnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在银行机构最小月申请次数")
    als_m12_cell_bank_max_inteday: Optional[str] = Field(None, description="按手机号查询，近 12 个月在银行机构申请最大间隔天数")
    als_m12_cell_bank_min_inteday: Optional[str] = Field(None, description="按手机号查询，近 12 个月在银行机构申请最小间隔天数")
    als_m12_cell_bank_week_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在银行机构周末申请次数")
    als_m12_cell_bank_week_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在银行机构周末申请机构数")
    als_m12_cell_bank_night_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在银行机构夜间申请次数")
    als_m12_cell_bank_night_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在银行机构夜间申请机构数")
    als_m12_cell_nbank_selfnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在本机构(本机构为非银)申请次数")
    als_m12_cell_nbank_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构申请次数")
    als_m12_cell_nbank_p2p_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构-改制机构申请次数")
    als_m12_cell_nbank_mc_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构-小贷机构申请次数")
    als_m12_cell_nbank_ca_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构-现金类分期机构申请次数")
    als_m12_cell_nbank_cf_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构-消费类分期机构申请次数")
    als_m12_cell_nbank_com_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构-代偿类分期机构申请次数")
    als_m12_cell_nbank_oth_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构-其他申请次数")
    als_m12_cell_nbank_nsloan_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构-持牌网络小贷机构申请次数")
    als_m12_cell_nbank_autofin_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构-持牌汽车金融机构申请次数")
    als_m12_cell_nbank_sloan_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构-持牌小贷机构申请次数")
    als_m12_cell_nbank_cons_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构-持牌消费金融机构申请次数")
    als_m12_cell_nbank_finlea_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构-持牌融资租赁机构申请次数")
    als_m12_cell_nbank_else_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构-其他申请次数")
    als_m12_cell_nbank_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构申请机构数")
    als_m12_cell_nbank_p2p_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构-改制机构申请机构数")
    als_m12_cell_nbank_mc_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构-小贷申请机构数")
    als_m12_cell_nbank_ca_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构-现金类分期申请机构数")
    als_m12_cell_nbank_cf_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构-消费类分期申请机构数")
    als_m12_cell_nbank_com_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构-代偿类分期申请机构数")
    als_m12_cell_nbank_oth_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构-其他申请机构数")
    als_m12_cell_nbank_nsloan_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构-持牌网络小贷机构申请机构数")
    als_m12_cell_nbank_autofin_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构-持牌汽车金融机构申请机构数")
    als_m12_cell_nbank_sloan_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构-持牌小贷机构申请机构数")
    als_m12_cell_nbank_cons_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构-持牌消费金融机构申请机构数")
    als_m12_cell_nbank_finlea_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构-持牌融资租赁机构申请机构数")
    als_m12_cell_nbank_else_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构-其他申请机构数")
    als_m12_cell_nbank_tot_mons: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构有申请记录月份数")
    als_m12_cell_nbank_avg_monnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构平均每月申请次数 (有申请月份平均)")
    als_m12_cell_nbank_max_monnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构最大月申请次数")
    als_m12_cell_nbank_min_monnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构最小月申请次数")
    als_m12_cell_nbank_max_inteday: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构申请最大间隔天数")
    als_m12_cell_nbank_min_inteday: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构申请最小间隔天数")
    als_m12_cell_nbank_week_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构周末申请次数")
    als_m12_cell_nbank_week_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构周末申请机构数")
    als_m12_cell_nbank_night_allnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构夜间申请次数")
    als_m12_cell_nbank_night_orgnum: Optional[str] = Field(None, description="按手机号查询，近 12 个月在非银机构夜间申请机构数")

    # 最早申请数据
    als_fst_id_bank_inteday: Optional[str] = Field(None, description="按身份证号查询，距最早在银行机构申请的间隔天数")
    als_fst_id_nbank_inteday: Optional[str] = Field(None, description="按身份证号查询，距最早在非银行机构申请的间隔天数")
    als_fst_cell_bank_inteday: Optional[str] = Field(None, description="按手机号查询，距最早在银行机构申请的间隔天数")
    als_fst_cell_nbank_inteday: Optional[str] = Field(None, description="按手机号查询，距最早在非银行机构申请的间隔天数")

    # 最近申请数据
    als_lst_id_bank_inteday: Optional[str] = Field(None, description="按身份证号查询，距最近在银行机构申请的间隔天数")
    als_lst_id_bank_consnum: Optional[str] = Field(None, description="按身份证号查询，最近开始在银行机构连续申请的次数")
    als_lst_id_bank_csinteday: Optional[str] = Field(None, description="按身份证号查询，最近开始在银行机构连续申请的持续天数")
    als_lst_id_nbank_inteday: Optional[str] = Field(None, description="按身份证号查询，距最近在非银行机构申请的间隔天数")
    als_lst_id_nbank_consnum: Optional[str] = Field(None, description="按身份证号查询，最近开始在非银行机构连续申请的次数")
    als_lst_id_nbank_csinteday: Optional[str] = Field(None, description="按身份证号查询，最近开始在非银机构连续申请的持续天数")
    als_lst_cell_bank_inteday: Optional[str] = Field(None, description="按手机号查询，距最近在银行机构申请的间隔天数")
    als_lst_cell_bank_consnum: Optional[str] = Field(None, description="按手机号查询，最近开始在银行机构连续申请的次数")
    als_lst_cell_bank_csinteday: Optional[str] = Field(None, description="按手机号查询，最近开始在银行机构连续申请的持续天数")
    als_lst_cell_nbank_inteday: Optional[str] = Field(None, description="按手机号查询，距最近在非银机构申请的间隔天数")
    als_lst_cell_nbank_consnum: Optional[str] = Field(None, description="按手机号查询，最近开始在非银机构连续申请的次数")
    als_lst_cell_nbank_csinteday: Optional[str] = Field(None, description="按手机号查询，最近开始在非银机构连续申请的持续天数")

